Homebrew/homebrew-test-bot

- .travis.yml
> Add Travis CI for testing.

- cmd/brew-test-bot.rb
Other taps haven't had the change to have a mass-update yet and we'll hold off doing that until we get our own house in order.
CC @ilovezfs
> Only run `brew style $FORMULA` on homebrew/core.

- cmd/brew-test-bot.rb
Needed for https://github.com/Homebrew/brew/pull/1145.
> Use `module_function`.

- cmd/brew-test-bot.rb
Don't limit cleanup to just Jenkins but always do it (e.g on Travis CI). CC @ilovezfs who mentioned this.
> test-bot: cleanup everywhere.

- cmd/brew-test-bot.rb
CC @ilovezfs who mentioned this.
> test-bot: clear stash before/after.

- cmd/brew-test-bot.rb
CC @ilovezfs should help with debugging
> test-bot: output build mode.

- cmd/brew-test-bot.rb
Test bot! Do not untap oneself!
> test-bot: do not untap test-bot tap.

- cmd/brew-test-bot.rb
Purge the GC log and PR locks on more repositories if they exist.
> Cleanup more weird Git edge-cases.

- cmd/brew-test-bot.rb
> brew-test-bot: Replace Utils::JSON with corelib JSON.

- .travis.yml
- cmd/brew-test-bot.rb
This is desirable to avoid a Homebrew/brew merge causing a failure in Homebrew/homebrew-core.
This PR will fail as-is but I want to figure out a way of getting this fixed in Homebrew/brew.
> Always run `brew doctor`.

- cmd/brew-test-bot.rb
> doctor: don't run on Linux.

- .travis.yml
- cmd/brew-test-bot.rb
Run `brew test-bot` on Linux to avoid breaking it again for Homebrew/brew.
> .travis.yml: also run on Linux.

- .travis.yml
- cmd/brew-test-bot.rb
Match the other taps more closely.
> travis.yml: more consistency changes.

- .travis.yml
- cmd/brew-test-bot.rb
Also, clear up some Travis CI logic.
> travis: use Xcode 8.1.

- cmd/brew-test-bot.rb
Some speedups and safety for Homebrew/brew.
> test-bot: cleanup more Travis CI logic.

- cmd/brew-test-bot.rb
Otherwise cruft in here will just continue to build up.
> Cleanup all HOMEBREW_PREFIX contents.

- cmd/brew-test-bot.rb
Otherwise these can get uploaded by e.g. Jenkins.
> Cleanup old bottles before build.

- cmd/brew-test-bot.rb
https://github.com/Homebrew/brew/pull/2256
> Don’t tap `caskroom/cask`.

- .travis.yml
Fix the (failing) Linux Travis CI build.
> .travis.yml: fix Linux build.

- cmd/brew-test-bot.rb
Fix some docs and Rubocop warnings.
> test-bot: general cleanup.

- cmd/brew-test-bot.rb
Use the Bintray API rather than assuming that a resolving entry in the CDN is enough to verify if a bottle is published.
> test-bot: improve Bintray published check.

- cmd/brew-test-bot.rb
When a formula is deleted the test bot run is currently a no-op. We may want to add more here in future
but to start with let's do a basic `brew uses` check to ensure no formulae still depend on it.
Also, while we're here: pluralise `@modified_formula` for consistency.
Requires https://github.com/Homebrew/brew/pull/2475 to work.
CC @ilovezfs for thoughts on any other omissions when we've deleted formulae.
> test-bot: handle deleted formulae.

- cmd/brew-test-bot.rb
This means it'll do a full build to check the formula logic too.
> test-bot: use --test-default-formula again.

- .travis.yml
And change HOMEBREW_DEVELOPER assignment format to be the same as Homebrew/brew.
> travis: cache gems, update Xcode.

- cmd/brew-test-bot.rb
Make use of the new Homebrew/brew environment variables (coming soon) for Bintray and the new method for clearing all sensitive environment variables.
> test-bot: change secret key handling.

- cmd/brew-test-bot.rb
Treat non-dependencies like conflicts and ensure they are unlinked before installation. This should avoid some opportunistic linking between formulae.
Similarly, relink dependencies when needed too.
Partially addresses https://github.com/Homebrew/brew/issues/2173 (at least for our CI)
> test-bot: unlink non-dependencies.

- .travis.yml
- cmd/brew-test-bot.rb
This change is pretty horrific but at least it'll verify basic errors in `--ci-upload`.
> Make `--dry-run` test `--ci-upload`.

- cmd/brew-test-bot.rb
Don't want to remove stuff from local testing of `test bot`.
> test-bot: only remove etc/var on --cleanup.

- cmd/brew-test-bot.rb
Instead of killing all of etc/var every time just delete the etc/var files that were installed from the bottle.
> test-bot: more conservatively cleanup etc/var.

- cmd/brew-test-bot.rb
When running jobs with multiple tests (e.g. "Homebrew Testing" jobs with multiple formula arguments passed) the `cleanup_before` and `cleanup_after` methods are called every time. Instead, we only want them called once on the first and last test respectively.
Fixes #75.
> test-bot: only cleanup before/after once.

- .travis.yml
- cmd/brew-test-bot.rb
Tweak our Travis CI configuration and the one we suggest for taps to be faster and use caching.
> Travis CI tweaks

- cmd/brew-test-bot.rb
Previously we only unlinked and relinked the dependency tree for the main formula but didn’t fix these up for `brew test`ing the bottled reverse dependencies.
This should address the issues building https://github.com/Homebrew/homebrew-core/pull/12985.
> test-bot: unlink and relink formulae for brew test.

- cmd/brew-test-bot.rb
Installed dependents may need to be relinked so unlink any conflicts.
> test-bot: unlink conflicts of installed dependents.

- cmd/brew-test-bot.rb
Clean up some of the extreme nesting and other weirdness used and setup
`brew style` so it will handle these in future.
> test-bot: RuboCop-prompted cleanup.

- cmd/brew-test-bot.rb
Maybe fixes https://github.com/Homebrew/brew/pull/2641.
> Simplify `coverage_args`.

- .travis.yml
Match those from Homebrew/brew.
> travis.yml: update cache locations.

- .travis.yml
Ensure the correct directories are cached.
> travis.yml: fix cache issues.

- cmd/brew-test-bot.rb
Related to #86, rescue from TapFormulaUnavailableError
during call to formula.recursive_dependencies
in unlink_conflicts (called by install_bottled_dependent)
and add the missing tap.
I found #86 when trying to `test-bot` a formula (ie. `osrf/simulation/gazebo7`) that depends on an untapped formula (ie. `cartr/qt4/qt@4`). For this PR, I found a problem when rebuilding a bottle for `ignition-transport`, which is a dependency of `gazebo7`. When trying to `install_bottled_dependent`, there was a call to `formula.recursive_dependencies` in `unlink_conflics` ([stacktrace here](https://gist.github.com/scpeters/7b3f46e672cd126507e06aab19e99030)).
> Tap if necessary during unlink_conflicts

- cmd/brew-test-bot.rb
Ensure that pkill is only run when necessary rather than failing when no processes are found.
CC @ilovezfs who spotted this.
> test-bot: tweak pkill logic.

- cmd/brew-test-bot.rb
Don't assume that Git commands are run in the correct repository but specify them explicitly instead.
> test-bot: ensure correct git directories.

- cmd/brew-test-bot.rb
> test-bot: use git -c not git config --global

- cmd/brew-test-bot.rb
Previously there were various assumptions about where a given `git` command would be run. Tear out the previous assumption-laden code in favour of explicitly having Git change to the destination directories where needed.
> test-bot: cleanup git usage.

- cmd/brew-test-bot.rb
Based on the Travis CI output tweak some of the formatting and add a safety check to ensure it'll work in future.
> test-bot: tweak formatting.

- cmd/brew-test-bot.rb
Output both the revision for `origin/master` and for `HEAD`.
> test-bot: tweak tap revision output.

- .travis.yml
This is to be consistent with the change in Homebrew/brew#2794.
> travis.yml: tweak how we handle homebrew/core.

- cmd/brew-test-bot.rb
https://github.com/Homebrew/brew/pull/3026
> Use refactored `curl_args`.

- cmd/brew-test-bot.rb
Add missing new_formula variable.
> test-bot: fix --keep-old option.

- .travis.yml
Try some stuff to debug then fix the build on Linux.
> Fix Linux build.

- .travis.yml
This matches the configuration in Homebrew/brew.
> Travis: update osx_image to xcode9

- cmd/brew-test-bot.rb
> test-bot: make some style fixes.

- cmd/brew-test-bot.rb
Reverts Homebrew/homebrew-test-bot#124
> Revert "test-bot: make some style fixes."

- .travis.yml
> travis.yml: always use vendored Ruby.

- cmd/brew-test-bot.rb
And move them around so they are used by `brew bottle` on upload.
> test-bot: set HOMEBREW_GIT_* vars.

- Formula/testbottest.rb
Let's make this integration test a little bit fuller.
> testbottest: use a few more DSL.

- cmd/brew-test-bot.rb
I maintain at least one formula with cross-tap dependencies ([osrf/simulation/gazebo7](https://github.com/osrf/homebrew-simulation/blob/master/gazebo7.rb#L29) depends on `cartr/qt4/qt@4`). In #91, I fixed a bug in `unlink_conflicts` related to this use case that rescues from `TapFormulaUnavailableError`, adds the missing tap, and tries again to call `recursive_dependencies` on a formula.
I just noticed there is an earlier place where a missing tap causes a problem: in the `run` function, a [formulae.each loop](https://github.com/Homebrew/homebrew-test-bot/blob/master/cmd/brew-test-bot.rb#L1105-L1111) is right after `homebrew`. 
The `formulae` function [calls brew deps](https://github.com/Homebrew/homebrew-test-bot/blob/master/cmd/brew-test-bot.rb#L1080) and then sorts the formulae so the …
> Check for untapped deps when sorting formulae

- .travis.yml
> travis.yml: fix bundler caching.

- Formula/testbottest.rb
> testbottest: use simpler expand_path.

- cmd/brew-test-bot.rb
When https://github.com/Homebrew/brew/pull/3875 has been merged ensure these are handled correctly by `test-bot`.
> test-bot: handle :test deps.

- cmd/brew-test-bot.rb
Reverts Homebrew/homebrew-test-bot#148
> Revert "test-bot: general cleanup."

- cmd/brew-test-bot.rb
Will add fix commit here.
Reverts Homebrew/homebrew-test-bot#149
> Revert "Revert "test-bot: general cleanup.""

- cmd/brew-test-bot.rb
not just for reverse dependencies.
> test-bot: install test deps for primary formulae

- cmd/brew-test-bot.rb
This is needed for https://github.com/Homebrew/brew/pull/3835.
> test-bot: set HOMEBREW_NEW_FORMULA_PULL_REQUEST_URL.

- .travis.yml
- cmd/brew-test-bot.rb
Also add dry-run test cases to travis to catch future errors like this.
Fixes #157
> test-bot: fix url_match array syntax

- .travis.yml
https://github.com/Homebrew/brew/pull/4352
> travis.yml: update to xcode 9.4

- cmd/brew-test-bot.rb
https://github.com/Homebrew/brew/pull/4590
> Enable `HOMEBREW_COLOR` on Travis.

- cmd/brew-test-bot.rb
> test-bot: fix --local docs.

- cmd/brew-test-bot.rb
Depends on https://github.com/Homebrew/brew/pull/4662.
> Update cache link logic.

- azure-pipelines.yml
- cmd/brew-test-bot.rb
This avoids having to add them in the YAML.
> test-bot: handle more Azure Pipeline settings automatically.

- cmd/brew-test-bot.rb
Use new method from https://github.com/Homebrew/brew/pull/4912 CC @fxcoudert
> Use ActiveSupport Hash#deep_merge

- cmd/brew-test-bot.rb
`TF_BUILD` is a bit more obvious.
> test-bot: use better Azure Pipelines variable.

- cmd/brew-test-bot.rb
This allows Homebrew/brew to consume these instead.
> test-bot: set CI environment variables.

- cmd/brew-test-bot.rb
Needed for https://github.com/Homebrew/brew/pull/4909.
> Remove `run_as_not_developer` calls.

- cmd/brew-test-bot.rb
Also, test this by ensuring Azure tap is correctly detected.
> test-bot: don't cleanup bottles or coverage.

- cmd/brew-test-bot.rb
We need to keep these around for future PRs.
> test-bot: don't delete osxfuse files.

- cmd/brew-test-bot.rb
Use the newly introduced constants and tweak how they are used so `Keg::TOP_LEVEL_DIRECTORIES` can be removed.
> test-bot: use new Keg directories.

- azure-pipelines.yml
> azure-pipelines: always upload test results.

- azure-pipelines.yml
- cmd/brew-test-bot.rb
- upload Azure coverage and Linux tests to match Homebrew/brew
- tweak test naming
- improve JUnit test output for Azure
> test-bot: improve tests output.

- cmd/brew-test-bot.rb
This will be a more general replacement of HOMEBREW_FORCE_HOMEBREW_ORG.
CC @sjackman FYI
> test-bot: set HOMEBREW_FORCE_HOMEBREW_ON_LINUX.

- cmd/brew-test-bot.rb
> test-bot: remove HOMEBREW_FORCE_HOMEBREW_ORG.

- .travis.yml
- README.md
- azure-pipelines.yml
- cmd/brew-test-bot.rb
We're using this as the primary CI now.
> README: use Azure Pipelines badge.

- cmd/brew-test-bot.rb
Apply the latest RuboCop fixes.
> brew-test-bot: fix brew style.

- cmd/brew-test-bot.rb
This PR enables building bottles on CircleCI.
> Add support for CircleCI

- cmd/brew-test-bot.rb
See https://github.com/Homebrew/brew/pull/5402
> Set HOMEBREW_CIRCLECI when on CircleCI

- azure-pipelines.yml
- cmd/brew-test-bot.rb
Apply changes from https://github.com/Homebrew/brew/pull/5448.
CC @jonchang @sjackman
> Fix Linuxbrew repository location and core tap.

- cmd/brew-test-bot.rb
When not using jenkins (for example when using AWS lambda for linuxbrew,
or even when manually uploading a bottle), the current error message
was "Missing Jenkins variables" when there were no bottles in the dir.
This may happen when no bottle has been built by the CI, or one
is trying to upload bottles from the wrong folder.
The new error messages have been improved and the path is also
displayed, to ease debugging.
There is one assumption here: when JENKINS_HOME is set, one has
to retrieve the bottles first (previously this code path
was triggered by the fact that there were no bottles in the
starting repository)
> brew-test-bot.rb: tweak missing bottles message when not using jenkins

- cmd/brew-test-bot.rb
This isn't a documented flag and doesn't do anything.
> test-bot: don't use unlink --force.

- Formula/testbottest.rb
Needed for https://github.com/Homebrew/brew/pull/5599.
> testbottest: remove deprecated :gcc_4_2.

- cmd/brew-test-bot.rb
This should better handle our limited diskspace in CI.
> test-bot: reduce cleanup prune.

- cmd/brew-test-bot.rb
If a formula is depended on by another formula changed in the same PR it should not be uninstalled.
A possible fix for #231 but need to confirm once merged.
> test-bot: avoid incorrectly uninstalling formula.

- cmd/brew-test-bot.rb
Rather than just the dependents.
> test-bot: check linkage of formula being tested.

- azure-pipelines.yml
Better mirror the Homebrew/brew configuration.
> azure-pipelines.yml: use Docker.

- cmd/brew-test-bot.rb
Some existing discussion: https://github.com/Homebrew/homebrew-core/pull/38435
> Run tests for test-dependents when a formula updates

- Formula/testbottest.rb
- cmd/brew-test-bot.rb
Also, use `brew style --fix` to cleanup formatting (and add those comments).
> Add frozen_string_literal comments.

- azure-pipelines.yml
This pull request upgrades Azure to use MacOS Mojave and Xcode 10.2.
/cc Homebrew/brew#6113, @MikeMcQuaid.
> Upgrade Azure to MacOS 10.14 and Xcode 10.2

- cmd/brew-test-bot.rb
Reverts Homebrew/homebrew-test-bot#255
> Revert "Fix detection of modified formulae on Azure"

- cmd/brew-test-bot.rb
> add ohai to help debug start and end diff sha1

- cmd/brew-test-bot.rb
kind of like #258, this PR outputs the added and modified formulae to help debug.
I could also add `deleted_formulae` if needed.
Let me know what you think.
> puts modified and added formulae

- cmd/brew-test-bot.rb
Depends on https://github.com/Homebrew/brew/pull/6291
> ci-upload: redact token in the log

- .github/workflows/tests.yml
- Dockerfile.yml
- azure-pipelines.yml
- cmd/brew-test-bot.rb
- Try to setup GitHub Actions CI
- Configure `brew test-bot` to handle the GitHub Actions CI environment variables.
- Cleanup some other CI provider code in `brew test-bot`.
> GitHub Actions CI

- azure-pipelines.yml
Ensure the information is passed through correctly on GitHub Actions.
> Setup Coveralls

- .travis.yml
Add Linux-only configuration to verify we don't break things
> (Re)add Travis CI configuration

- cmd/brew-test-bot.rb
Print a big warning so people understand what's going on.
CC @dawidd6 for thoughts.
Closes: #282
> test-bot: better handle missing CI variables.

- cmd/brew-test-bot.rb
Used `brew style --fix Homebrew/test-bot`.
> brew-test-bot: fix code style.

- cmd/brew-test-bot.rb
Fixes problems with detection of modified formulae on taps other than core.
> Check if merge commit and CoreTap and OS.linux

- Dockerfile
> Dockerfile: use homebrew.

- README.md
Also: remove Azure Pipelines badge.
> README: note CI providers

- cmd/brew-test-bot.rb
I don't know if it will work, will test here.
> test-bot: allow colors on Azure

- lib/test_bot.rb
> test_bot: add missing FileUtils.

- cmd/brew-test-bot.rb
- lib/test.rb
- lib/test_bot.rb
Delete more code that's no longer required post-#299.
> Delete more coverage code.

- lib/test_bot.rb
Closes: https://github.com/Homebrew/homebrew-test-bot/issues/302
> test-bot: checkout/reset if pr

- lib/test.rb
Ensure that every time we install a new formula or bottled dependent that we check the state of the disk usage and nuke HOMEBREW_CACHE if it has got too full.
> lib/test: cleanup during build.

- lib/test.rb
- lib/test_bot.rb
None of this should change behaviour.
> lib: fix some rubocop style complaints.

- azure-pipelines.yml
- lib/test.rb
- lib/test_bot.rb
- Don't try to publish test results on Azure Pipelines
- Remove Jenkins branch/pipeline support (no-one uses these)
- Fix Jenkins pull request builder detection
> Fix CI provider logic

- lib/test.rb
> lib/test: fix typo.

- lib/test.rb
Reverts Homebrew/homebrew-test-bot#314
> Revert "test: set HOMEBREW_BOTTLE_SUDO_PURGE."

- lib/test.rb
Reverts Homebrew/homebrew-test-bot#315, reapplies #314
> test: set HOMEBREW_BOTTLE_SUDO_PURGE.

- lib/test.rb
> lib/test: fix detection of Homebrew Testing jobs.

- lib/test.rb
Specify formulae where we want to test build dependants.
Prompted by discussion in https://github.com/Homebrew/homebrew-test-bot/pull/295. CC @Bo98 for thoughts.
> test: add --include-build whitelist.

- lib/test.rb
- lib/test_bot.rb
- spec/homebrew/test_spec.rb
Fixes #330.
Disclaimer: test.rb is pretty much entirely untested. Testing was limited to `brew test-bot --ci-upload --dry-run` and `brew style homebrew/test-bot`.
> Use /usr/bin/git

- lib/test.rb
> test: skip dependents where requirements aren't satisfied

- lib/test_bot.rb
```
Error: undefined method `CURL' for Homebrew::TestBot:Module
/var/lib/jenkins/workspace/Homebrew Bottles/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:257:in `block (2 levels) in test_ci_upload'
/var/lib/jenkins/workspace/Homebrew Bottles/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:213:in `each'
/var/lib/jenkins/workspace/Homebrew Bottles/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:213:in `block in test_ci_upload'
/var/lib/jenkins/workspace/Homebrew Bottles/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:204:in `each'
/var/lib/jenkins/workspace/Homebrew Bottles/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:204:in `test_ci_upload'
/var/lib/jenkins/workspace/Homebrew Bottles/Library/Taps/homebrew/homebrew-test-bot/lib/test_bot.rb:338:in …
```
> test_bot: fix curl regression

- lib/test.rb
Should no longer be needed as of 10.15.4.
> lib/test: remove HOMEBREW_BOTTLE_SUDO_PURGE.

- lib/test.rb
Still needed 😭 
Reverts Homebrew/homebrew-test-bot#348
> Revert "lib/test: remove HOMEBREW_BOTTLE_SUDO_PURGE."

- lib/test_bot.rb
Changed in https://github.com/Homebrew/brew/pull/7285
> test_bot: fix constant usage.

- lib/test.rb
And unconditionally run `brew style`.
Depends on merge of https://github.com/Homebrew/brew/pull/7370.
> test: run brew audit --skip-style

- .github/workflows/tests.yml
Now that GitHub Actions includes Linuxbrew.
> workflows/tests: handle system Linuxbrew.

- .github/workflows/tests.yml
- Gemfile
- Gemfile.lock
- cmd/test-bot.rb
- lib/step.rb
- lib/test.rb
- lib/test_bot.rb
- spec/spec_helper.rb
Reverts Homebrew/homebrew-test-bot#355
> Revert "Delete unused code."

- .github/workflows/tests.yml
- Gemfile
- Gemfile.lock
- cmd/test-bot.rb
- lib/step.rb
- lib/test.rb
- lib/test_bot.rb
- spec/spec_helper.rb
Take #2 of https://github.com/Homebrew/homebrew-test-bot/pull/355 but with `--ci-upload` non-Jenkins bits kept around and the omissions pointed out by @Bo98.
> Delete unused code.

- cmd/test-bot.rb
- lib/test_bot.rb
- Move to `lib/test_bot.rb` (no reason it can't live here now)
- Create both the `home` and `logs` directories.
> test_bot: tweak home/logs.

- cmd/test-bot.rb
- lib/test_bot.rb
And use this on GitHub Actions self-hosted runners.
Without it too much stuff goes boom.
> test_bot: readd --local.

- lib/test_bot.rb
Do a loop even with a single argument to simplify.
> test_bot: DRY Test.new call.

- .github/workflows/tests.yml
Linuxbrew seems to be popping in and out of images so need to handle whether it is present or not.
> workflows/tests: handle no Linuxbrew.

- cmd/test-bot.rb
The default VMs ship with some stuff that makes `brew doctor` sad.
> cmd/test-bot: cleanup by default on GitHub Actions.

- cmd/test-bot.rb
- lib/test.rb
This has been essentially the default for a while and is more unused code that can be deleted to reduce complexity.
> Remove --no-pull

- lib/test.rb
- run `setup` first
- rename `readall` to `tap_syntax` (as it runs `style` and `readall`)
- add `test_formulae` which sets things up for formulae and does all testing.
- create `all_steps_passed?` method
This may look a bit pointless but should enable running individual steps in future (to improve output on e.g. GitHub Actions).
> lib/test: reorder, rename steps.

- .github/workflows/tests.yml
Matches homebrew/core code to catch any issues with that before they hit there.
> workflows/tests: output steps_output.

- lib/test.rb
Also, rearrange those functions to ensure that Homebrew/brew has been cleaned before we run more `brew` commands.
> lib/test: move more logic to cleanup functions.

- lib/step.rb
- lib/test.rb
- spec/stub/utils.rb
- Don't use `/usr/bin/git` when `git` will do
- Output what method is being run each time
> lib: cleanup output.

- lib/test_bot.rb
- lib/test_ci_upload.rb
> Extract TestCiUpload module

- lib/test.rb
- lib/test_bot.rb
- lib/test_runner.rb
- lib/tests/tap_syntax.rb
- spec/homebrew/test_spec.rb
This is the first part of moving every independent test into its own class.
This will make coupling/state clearer between tests.
> Extract Tests::TapSyntax

- lib/test.rb
- lib/test_runner.rb
- lib/tests/cleanup.rb
Next part of splitting Test into separate classes.
> Extract Tests::Cleanup

- .gitignore
- lib/test.rb
- lib/test_runner.rb
- lib/tests/cleanup.rb
- lib/tests/formulae.rb
- lib/tests/setup.rb
- lib/tests/tap_syntax.rb
- spec/homebrew/tests/setup_spec.rb
- Strip down the public interface to be as minimal as possible
- Avoid using instance variables from parent classes
- Move some shared logic to `Test`
> Refactor Test classes

- cmd/test-bot.rb
- lib/test.rb
- lib/tests/tap_syntax.rb
Default the tap to the core tap (homebrew-core or linuxbrew-core).
> Tweak tap handling

- lib/tests/formulae.rb
- Check if we can find `origin/$GITHUB_BASE_REF`. If not: fetch it.
- Explicitly use GitHub Actions SHA if available (and no base ref).
- Only print "no CI provider detected!" if we have some inclination this is a CI job.
- Reorder `HEAD` output for consistency.
- Add a `rev_parse` function to DRY things up a bit.
> tests/formulae: better handle GitHub Actions checkout

- lib/tests/formulae.rb
This should help figure out why these values aren't being set.
> formulae: more GitHub Actions SHA1 debugging output.

- lib/tests/formulae.rb
This avoids overwriting good values with empty strings.
> tests/formulae: check that some variables are present before use.

- lib/tests/formulae.rb
Now that GitHub Actions is nailed down again avoid spamming.
> tests/formulae: remove debugging output.

- .github/workflows/tests.yml
Make the workflow a bit more Linux friendly.
> workflows/tests: Linux tweaks.

- lib/test_runner.rb
Needed for https://github.com/Homebrew/brew/pull/7509
> test_runner: duplicate Homebrew.args.named.

- cmd/test-bot.rb
This is useful in debugging issues.
> test-bot: add --debug switch.

- .github/workflows/tests.yml
Avoid setup.rb being incorrectly cached.
> workflows/tests: tweak caching

- lib/tests/formulae.rb
Fix deprecations from https://github.com/Homebrew/brew/pull/7579
> formulae: use latest_version_installed?

- lib/test_bot.rb
- lib/test_cleanup.rb
Debug why in Homebrew/brew it's resetting when a tap isn't present.
> test_bot: output tap more often.

- cmd/test-bot.rb
- lib/test.rb
- lib/test_bot.rb
- lib/test_cleanup.rb
- lib/test_runner.rb
Otherwise in Homebrew/brew we reset to origin/master incorrectly.
> Only set CoreTap tap default for checking syntax.

- lib/step.rb
Needed for https://github.com/Homebrew/brew/pull/7622.
> lib/step: use delete_prefix.

- lib/test_ci_upload.rb
chuzzle has been deprecated and removed
> test_ci_upload: use chomp instead of chuzzle

- lib/test_ci_upload.rb
See https://github.com/Homebrew/homebrew-test-bot/pull/408/files#r429566183
> test_ci_upload: use chomp.presence.

- lib/tests/formulae.rb
Use this new flag. Depends on https://github.com/Homebrew/brew/pull/7684.
> formulae: brew audit --git.

- Dockerfile
https://github.com/Homebrew/homebrew-test-bot/pull/422
> Dockerfile: base on latest master build

- .gitignore
- lib/test.rb
- lib/test_cleanup.rb
- lib/tests/formulae.rb
I don't think this is actually used anywhere.
> Remove brewbot_root

- lib/test_cleanup.rb
* Ensure permissions are correct to ensure deletion is a success.
* Cover hidden files & directories (so that we can also check the permissions of them).
Permission fixing is one pass while deletion is second pass. This is so we don't try to delete a parent directory before we've managed to fix the permissions of its children, as that will fail.
> lib/test_cleanup: more rigorous and reliable file deleting

- lib/test_cleanup.rb
- spec/spec_helper.rb
See https://github.com/Homebrew/brew/pull/7867.
> Fix brew style.

- .github/workflows/tests.yml
- cmd/test-bot.rb
- lib/tests/formulae.rb
Don't set it by default (because it's not super reliable).
> Require --test-default-formula to be manually specified.

- lib/tests/formulae.rb
Allow there to be no changes but still test `testbottest`.
> formulae: tweak formula test logic.

- lib/tests/formulae.rb
If `GITHUB_REPOSITORY` is not the same as the tap being used, then we should not be considering `GITHUB_SHA` etc.
This is the case in Homebrew/brew, but could in theory be elsewhere through the use of `--tap`.
Also revert to `popen_read` for `rev_parse` since it seems to be intentionally designed in a way that it returns nothing if it can't find the revision.
Technically, this should probably check `remote` rather than `full_name`, in case someone is using a non-conventional repository name.
(The split into a separate function is to satisfy Rubocop)
> lib/tests/formulae: check GITHUB_REPOSITORY

- lib/tests/formulae.rb
`brew deps` is allowed to fail here so we can't use `safe_popen_read`. However, we should still make sure it is failing for reason we think it is and abort otherwise.
> lib/tests/formulae: fix handling of non-core dependencies

- .github/workflows/tests.yml
- lib/tests/cleanup_before.rb
Test that `--only-setup` ends up green on a default configuration.
> workflows/tests: test cleanup/setup/syntax.

- lib/tests/tap_syntax.rb
Requires https://github.com/Homebrew/brew/pull/8231.
> tap_syntax: audit a single tap.

- .github/workflows/tests.yml
- lib/tests/formulae.rb
These are done by setup-homebrew.
> workflows/tests: remove unnecessary steps.

- lib/tests/formulae.rb
This was fetched only if it was completely missing but we want to do so unconditionally under GitHub Actions.
> lib/tests/formulae: fetch origin/master.

- lib/tests/formulae.rb
Revert: https://github.com/Homebrew/homebrew-test-bot/pull/469
> Revert "formulae: popen_read for git merge-base"

- lib/tests/formulae.rb
Another try to fix modified formulae detection.
> formulae: fully fetch origin/master

- lib/tests/formulae.rb
Reverts Homebrew/homebrew-test-bot#477
> Revert "formulae: use full names"

- lib/test_cleanup.rb
This works out what the actual default branch is before resetting
> Don't assume the default branch is master

- lib/test_cleanup.rb
Closes: https://github.com/Homebrew/homebrew-test-bot/issues/481
> cleanup: fix variable name

- Formula/testbottest.rb
- lib/test_bot.rb
- lib/tests/cleanup_before.rb
- lib/tests/formulae.rb
- spec/stub/utils.rb
Needed for Homebrew/brew#8542.
> Fix RuboCop violations.

- lib/tests/formulae.rb
Change from whitelist to allowlist.
> formulae: use allowlist terminology

- lib/test_ci_upload.rb
- lib/test_cleanup.rb
- lib/tests/cleanup_after.rb
- spec/stub/development_tools.rb
- spec/stub/formula.rb
- spec/stub/formula_installer.rb
- spec/stub/utils/bottles.rb
For https://github.com/Homebrew/brew/pull/8556
> Fix brew style

- spec/stub/development_tools.rb
- spec/stub/formula.rb
- spec/stub/formula_installer.rb
- spec/stub/utils/bottles.rb
For some reason these didn't show up in the previous PR as failures.
> spec/stub: add frozen_string_literal.

- lib/tests/formulae.rb
This PR adds a `brew livecheck` test, so we can test it on CI.
cc @samford @nandahkrishna
> formulae: run brew livecheck

- lib/tests/formulae.rb
Required for https://github.com/Homebrew/brew/pull/8851
> lib/tests/formulae.rb: specify --formula in 'brew list'

- cmd/test-bot.rb
- lib/step.rb
- lib/tests/formulae.rb
Update manpage text to match existing contents of `brew` manpage.
> test-bot: update manpage text

- lib/tests/formulae.rb
This should help debug the CI issues.
> tests/formulae: output stderr for `brew uses`.

- lib/test_cleanup.rb
- lib/tests/cleanup_before.rb
Add helper function for (re)moving files depending on whether the runner is ephemeral or not.
> Move files where possible instead of deleting them.

- lib/test.rb
- lib/test_cleanup.rb
- Remove unused `change_git!` method.
- Remove no longer needed debugging text.
> lib: cleanup more test logic.

- lib/test_cleanup.rb
I didn't mean to remove this code 🤦‍♂️.
> test_cleanup: fix bad revert.

- lib/tests/formulae.rb
Closes #562.
Closes https://github.com/Homebrew/homebrew-core/pull/69708.
Thanks, @bayandin.
> tests/formulae: don't skip new formulae

- .github/workflows/tests.yml
- lib/test_bot.rb
Point to `brew pr-upload` instead.
> lib/test_bot: deprecate --ci-upload.

- lib/test_ci_upload.rb
> lib/test_ci_upload: fix Style/RedundantBegin offence

- lib/tests/formulae.rb
https://github.com/Homebrew/homebrew-test-bot/pull/594#pullrequestreview-629273173
> lib/tests/formulae: cleanup_during logic fix

- .github/workflows/tests.yml
Reverts Homebrew/homebrew-test-bot#602
> Revert "build(deps): bump actions/cache from v1 to v2.1.5"

- cmd/test-bot.rb
- lib/test_cleanup.rb
- lib/tests/cleanup_after.rb
- lib/tests/cleanup_before.rb
Provide temporary migration path from `GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED`.
> Use `GITHUB_ACTIONS_HOMEBREW_MACOS_SELF_HOSTED` variable

- lib/tests/formulae.rb
See:
https://github.com/Homebrew/homebrew-core/pull/80242
This prevents endless builds, and tests on formulae that are
not yet ready for Linux
> tests: do not test dependent formulae with :all bottles on Linux

- cmd/test-bot.rb
- lib/tests/formulae.rb
Migrate some environment variables into arguments.
> Add more arguments.

- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
Remove some logic that's been fixed in homebrew/core.
Depends on https://github.com/Homebrew/homebrew-core/pull/80808
> lib/tests/formulae*: homebrew-core cleanup.

- lib/tests/formulae_detect.rb
Continuation of: https://github.com/Homebrew/homebrew-test-bot/pull/643
> formulae_detect: git fetch origin only if not official tap

- cmd/test-bot.rb
- lib/test_runner.rb
As suggested in https://github.com/Homebrew/homebrew-test-bot/pull/636#discussion_r667354914
> cmd/test-bot: use `comma_array`.

- lib/tests/formulae_dependents.rb
See discussion in: https://github.com/Homebrew/homebrew-core/pull/81485
> formulae_dependents: install glibc if needed

- lib/tests/formulae_dependents.rb
Discussion here: https://github.com/Homebrew/homebrew-core/pull/81485
> formulae_dependents: skip dependents tests in wheezy container

- lib/tests/formulae.rb
As discovered by @cho-m in https://github.com/Homebrew/homebrew-core/pull/84136
> formulae: actually enable new formulae tests on Linux

- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
During formula build or test, we need to unset `HOMEBREW_GIT_PATH` if the formula in question has a `depends_on "git"`, otherwise it will continue to prioritise system git in the PATH.
In these scenarios, it is also safe to assume brewed git is functional, otherwise something's already broken and the build/test is going to fail anyway.
> lib/tests/formulae*: unset HOMEBREW_GIT_PATH for git dependents

- lib/tests/formulae.rb
> lib/tests/formula: install curl if `HOMEBREW_FORCE_BREWED_CURL` is set

- lib/test_bot.rb
> lib/test_bot: always use system curl where possible

- lib/tests/formulae_dependents.rb
We already use the `bottled?` method from `test-bot` elsewhere, so it
seems better to be consistent about it. While we're doing that, let's
make sure to handle `:all` bottles appropriately.
> formulae_dependents: refactor to use `bottled?` test-bot method

- lib/step.rb
- Use early `return`s to reduce indentation
- Use `<details>` to optionally display the full output for the failed command in the annotation.
> lib/step: tweak annotation code/output.

- lib/step.rb
This doesn't seem to render correctly at the moment.
> lib/step: more annotation format tweaks

- lib/step.rb
- clarify that these are GitHub Actions annotations in method name
- don't duplicate the output on GitHub Actions
- better truncate the output
- note the OS and architecture in the title
> lib/step: improve GitHub Actions annotations.

- lib/step.rb
See https://github.com/Homebrew/homebrew-test-bot/pull/710#discussion_r752419047 and https://github.com/Homebrew/homebrew-test-bot/pull/361
> lib/step: don't use .present on output.

- lib/tests/formulae.rb
> formulae: fix missing `=`

- lib/step.rb
Those should work now after recent changes to workflows.
https://github.com/Homebrew/homebrew-core/pull/89586
> lib/step: enable annotations on Linux

- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
See discussion at Homebrew/brew#12454.
> Add tests for opportunistic linkage

- cmd/test-bot.rb
This will be a no-op after #687.
Merge after #687 and Homebrew/homebrew-core#87871.
> cmd/test-bot.rb: remove `--skip-unbottled-{arm,linux}`

- lib/tests/formulae.rb
Fixes skipping bottle builds for PRs that add a formula and switch other
formulae to depend on the added formula.
Let's also make this skipping behaviour more prominent so that it's more
obvious when it's happening.
> formulae: check for added formulae in `build_bottle?`

- lib/tests/formulae.rb
This just produces an error otherwise.
> formulae: call `new`

- lib/test_formulae.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
Fixes CI failures in Homebrew/homebrew-core#89642.
> formulae_dependents: install subversion, etc when needed

- cmd/test-bot.rb
- lib/test_cleanup.rb
- lib/tests/cleanup_after.rb
- lib/tests/cleanup_before.rb
Rename env to `GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED`.
> Apply self-hosted logic to Linux

- Gemfile
- Gemfile.lock
Port https://github.com/Homebrew/brew/pull/12575 to here.
> Gemfile: restrict activesupport version range

- .github/workflows/tests.yml
`actions/setup-ruby` is deprecated.
> workflows/tests: use ruby/setup-ruby

- lib/test_cleanup.rb
Fixes situations where some PRs permanently damage VMs until manual intervention.
> test_cleanup: fix cleanup for broken directory executable bits

- lib/tests/formulae.rb
The existing `livecheck_info.first["version"]["newer_than_upstream"]` line assumes that the first object in the JSON array will contain a `"version"` hash. This is true when the check is successful:
```json
{
"formula": "example",
"version": {
"current": "1.2.3",
"latest": "1.2.3",
"outdated": false,
"newer_than_upstream": false
}
}
```
However, a `"version"` hash isn't present when an error is encountered:
```json
{
"formula": "example",
"status": "error",
"messages": [
"curl: (6) Could not resolve host: example.com"
],
"meta": {
"livecheckable": true
}
}
```
`test-bot` doesn't account for a `nil` `"version"` value and this is currently producing an ```Error: undefined method `[]' for nil:NilClass``` error on CI. This PR addresses the issue by accounting for a `nil` `"version"` value. …
> Handle livecheck error conditions

- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
Needed due to https://github.com/Homebrew/brew/pull/13790
> test-bot: use `--eval-all`.

- cmd/test-bot.rb
> cmd: remove GITHUB_ACTIONS_HOMEBREW_MACOS_SELF_HOSTED

- lib/tests/formulae.rb
See https://github.com/Homebrew/brew/pull/14095
> tests/formulae: use --no-all-checks

- lib/test_bot.rb
Closes https://github.com/Homebrew/brew/issues/14274
> Set PYTHONDONTWRITEBYTECODE when running tests.

- lib/tests/formulae.rb
Having an alternative version of a dependency linked could result in
unintended linkage with the wrong version. This occurs, for example,
in Homebrew/homebrew-core#124227.
Let's fix that by unlinking alternative dependency versions that do not
appear in the tested formula's dependency tree.
> formulae: unlink alternative versioned dependencies

- lib/tests/formulae_dependents.rb
Added in https://github.com/Homebrew/brew/pull/15042
> formulae_dependents: use `--skip-post-install`

- lib/tests/tap_syntax.rb
- Make checks a bit stricter
- Only remove directory if we created it
> tests/tap_syntax: safer API generation.

- lib/tests/formulae.rb
Some check suites will have multiple of these (e.g. when a PR is closed
and then reopened), so let's use the latest run available.
> formulae: use bottles from latest CI run

- lib/test_formulae.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
This will allow us to speed up dependent testing in PRs that touch
multiple formulae.
Will also need changes in Homebrew/actions#373.
> formulae_dependents: cache dependent testing results

- .github/workflows/tests.yml
- lib/test_formulae.rb
- lib/tests/formulae.rb
This helps make sure there are no changes that we don't expect to the
bottles that we create.
> Implement bottle checksum verification

- lib/test_formulae.rb
Workflow modifications can be used to compromise our cache, and we don't
want that.
> test_formulae: avoid caching PRs that have the `workflows` label

- lib/test_formulae.rb
This allows us to avoid calling the REST API to request for the commit's
`node_id`.
> test_formulae: replace `node` query with `repository` query

- lib/test_formulae.rb
Some of this logging is a bit redundant, so let's skip it.
> Reduce bottle install logging

- lib/test_formulae.rb
This revision will typically be a merge commit that doesn't appear in
the PR branch, so it would be useful to show additional information
about it.
> test_formulae: improve bottle install logging

- lib/tests/formulae.rb
These tests are a bit flaky, and I think we'd rather deal with any
failures from these checks after the migration rather than have them
hold it up.
> tests/formulae: skip online checks for OpenSSL migration PRs

- lib/test_bot.rb
See discussion at Homebrew/actions#393.
> test_bot: copy global `.gitconfig` with `--local`

- lib/test_formulae.rb
Fixes/see https://github.com/Homebrew/homebrew-core/actions/runs/5622769066/job/15236229632?pr=137225#step:3:26 for https://github.com/Homebrew/homebrew-core/pull/137225 CC @chenrui333 @carlocab
> test_formulae: correct artifact ID type.

- lib/tests/setup.rb
> tests/setup: also install livecheck gems

- lib/tests/formulae_dependents.rb
Mitigation for GitHub network issues.
> tests/formulae_dependents: fetch all dependent dependencies with retries

- lib/tests/formulae_dependents.rb
We should probably add CI coverage of dependents here at some point.
> tests/formulae_dependents: fix variable scope

- lib/tests/formulae_detect.rb
Idea here is to only run fetch checks in the merge queue for formulae where the `pkg_version` or bottle block have changed. This exempts e.g. `brew style` changes from having to go through bottle fetch tests.
Requires workflow changes to take effect, but the logic can be monitored to see if it's working before that since we print the output here.
Requires Homebrew/brew#16130.
> tests/formulae_detect: check for formulae with version or bottle changes

- cmd/test-bot.rb
- lib/tests/formulae.rb
Requires https://github.com/Homebrew/brew/pull/16466 May be needed to unblock https://github.com/Homebrew/homebrew-core/pull/159760
> Allow skipping the revision audits.

- lib/test_bot.rb
- lib/tests/formulae_dependents.rb
- spec/global.rb
For https://github.com/Homebrew/brew/pull/16497 and https://github.com/Homebrew/brew/pull/16501
> Fix RuboCop `Style/{ArrayIntersect,RedundantFreeze}` offenses

- lib/step.rb
- spec/stub/system_command.rb
- spec/stub/utils.rb
I think this might resolve https://github.com/Homebrew/brew/actions/runs/7675446094/job/20921701555?pr=16540 but I'm starting to get out of my comfort/comprehension zone
> explicitly include SystemCommand::Mixin where needed

- lib/step.rb
- lib/test.rb
- lib/test_bot.rb
- lib/test_formulae.rb
- lib/test_runner.rb
- lib/tests/bottles_fetch.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
- lib/tests/formulae_detect.rb
- spec/homebrew/step_spec.rb
For https://github.com/Homebrew/brew/pull/16848
> Use RuboCop default hash syntax.

- lib/test_formulae.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
Companion to Homebrew/actions#529.
> test_formulae: support globbing artifacts

- lib/tests/setup.rb
These are all needed by various stages of installing formulae.
> tests/setup: install more bundler gems.

- lib/tests/formulae.rb
> tests/formulae: pass `--formula` more often

- lib/tests/bottles_fetch.rb
> bottles_fetch: fail when formula has no bottles

- cmd/test-bot.rb
- lib/test.rb
- lib/test_bot.rb
- lib/test_formulae.rb
- lib/test_runner.rb
- lib/tests/cleanup_after.rb
- lib/tests/formulae.rb
This is a nicer format and will get analytics.
> cmd/test-bot: migrate to AbstractCommand

- lib/test_formulae.rb
Potential regression https://github.com/Homebrew/homebrew-test-bot/pull/1186#issuecomment-2307157215
Reverts Homebrew/homebrew-test-bot#1186
> Revert "test_formulae: improve accuracy of `#bottled?`"

- lib/tests/formulae.rb
At least I got conditional right...
> formulae: fix comment

- lib/step.rb
GitHub Actions seems to truncate our annotations to 4KB, so let's adjust
to truncating at 4KB instead.
Since 4KB isn't a lot, let's drop the line count handling, and reduce
the number of context lines we have for error messages.
While we're here, let's also avoid truncating the start of our output in
the middle of a line, since that makes the first line of our annotation
less intelligible.
> Truncate annotation bodies to 4KB

- lib/step.rb
- lib/tests/formulae_dependents.rb
Needed for https://github.com/Homebrew/brew/pull/18255.
> `brew style --fix` for Rubocop update

- lib/test_runner.rb
- lib/tests/formulae_detect.rb
This reverts commit 2abe00d85a4662a2a86e65cb62e64dea416605c2.
revert https://github.com/Homebrew/homebrew-test-bot/pull/1410
> Revert "feat: scope detection to all packages"

- lib/test_formulae.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
Needed for https://github.com/Homebrew/brew/pull/20244
> Fix `brew style`

- Formula/t/testbottest.rb
- For https://github.com/Homebrew/brew/pull/20402.
> testbottest: Specify HEAD branch

- lib/tests/setup.rb
To help us catch a problem that causes CI jobs to hang.
> tests/setup: run `brew doctor` with `--debug`

- lib/tests/formulae.rb
* Don't run sudo purge to see if Sequoia bug is fixed
* Avoid installing GCC into build environment when we don't have an explicit dependency as it results in unwanted bottles
---
We previously discussed sudo purge in #1552 but didn't get around to it. Since check was only for Sequoia, at least Tahoe has been running without it.
May need someone to double check on GCC installation, but I think majority of cases that use this results in bypassing our linux_only_gcc_dependency audit.
> tests/formulae: remove workarounds
