Homebrew/homebrew-test-bot

- cmd/brew-test-bot.rb
I believe that `brew man` is not part of CI. This runs it in the test-bot and verifies that it doesn't cause any changes to the tracked files. I put this very early in the test-bot loop to speed up testing, but we could put it elsewhere. I believe the master branch of brew currently will fail this test.
> Test that brew man changes no files

- cmd/brew-test-bot.rb
Use this to ensure that tag updating isn't broken.
> Run update-test --to-tag.

- cmd/brew-test-bot.rb
This is no longer needed as it's in an external repository now.
> brew-test-bot: no need to hide from manpage.

- cmd/brew-test-bot.rb
Currently if there's a style violation in a single file then it shows up 2-3 times (`brew audit --new-formula`, `brew style`, `brew style homebrew/core`) and that's a bit silly.
> brew-test-bot: only check style once.

- cmd/brew-test-bot.rb
Also check the `ROOT_BUILD_CAUSE_GHPRBCAUSE` variable which can be another indicator of it being a pull request. CC @ilovezfs
> test-bot: improve Jenkins PR detection.

- cmd/brew-test-bot.rb
It passes `brew style` so whitelist it to be checked. This will allow more taps to be added in future.
> Use Rubocop to check homebrew/versions style.

- cmd/brew-test-bot.rb
This was removed when we were stuck on Ruby 1.8 due to terrible performance but it should now be fine to re-enable.
CC @ilovezfs for thoughts.
> Use uses --recursive.

- cmd/brew-test-bot.rb
When the diff contains an `or_later` bottle change then don’t try to
build the bottle but just install it and test it that way.
CC @ilovezfs for thoughts.
> Test or_later formula changes.

- cmd/brew-test-bot.rb
- escape `\` in regex to be passed to `git diff`
- specify the commit to check
> Fix `or_later` detection.

- cmd/brew-test-bot.rb
When brew-test-bot is called with `--keep-old` it will pass this flag to
the `bottle` command. For new formulae this results in an error.
> Do not propagate keep-old flag for new formulae

- cmd/brew-test-bot.rb
I could have got this entirely wrong (I'm not even entirely sure how to test this!), but all of Homebrew/brew's builds seem to be failing with this error or similar:
> Error: No such file or directory - /Users/brew/Jenkins/pr-brew/version/any_sierra/Library/Homebrew/test/testbottest.rb
Homebrew/brew has a file called testbottest, but it's at Library/Homebrew/test/support/fixtures/testbottest.rb. So, my guess is that it was moved, and that's what's causing the failures.
It's very possible I'm wrong though! It looks like it's been absent since Homebrew/brew@4db1317f38f5a55574854e7bf1dfe4379e807b4f, though, so I can't guess why it only started failing very recently.
> Update testbottest path

- cmd/brew-test-bot.rb
This is unnecessary now we have `brew style` and it checks whatever taps are currently tapped (which is not desirable).
CC @woodruffw
> Don't run Homebrew/brew `brew readall --syntax`.

- cmd/brew-test-bot.rb
As they can't be securely uploaded anywhere for PRs.
Also, set `--build-from-source` correctly when `--no-bottle` is passed.
> Don't build bottles by default on Travis CI.

- cmd/brew-test-bot.rb
This means things like e.g. cleanup are done automatically. This is a dangerous operation but Travis CI boxes are transient anyway.
> Default --ci-auto to on for Travis CI.

- cmd/brew-test-bot.rb
This means we can save some CPU cycles on our Jenkins boxes.
> test-bot: record coverage on Travis CI again.

- cmd/brew-test-bot.rb
Follow-up to #35; see https://bot.brew.sh/job/Homebrew%20Bottles/65369/console:
```
brew pull --clean https://github.com/Homebrew/homebrew-emacs.git/pull/515
Error: Not a GitHub pull request or commit: https://github.com/Homebrew/homebrew-emacs.git/pull/515
```
> Revert "Use tap.remote for pull_pr for Linuxbrew"

- cmd/brew-test-bot.rb
Get the tap slug from `CIRCLE_REPOSITORY_URL`.
> resolve_test_tap: Fix for Circle CI

- cmd/brew-test-bot.rb
As this will be an integration test doing things that require the
internet we may as well use `brew audit --online` to run any additional,
online-only tests (e.g. https://github.com/Homebrew/brew/pull/1637).
> Always run `brew audit strict --online`.

- cmd/brew-test-bot.rb
This makes more sense now we're killing our own ones of these taps.
> Match `brew audit` devel/head-only logic.

- cmd/brew-test-bot.rb
This should improve pull requests with lots of conflicting formulae in the same PR. Additionally, it’ll test that this linkage check isn’t required any longer.
> Don't require dependencies to be linked

- cmd/brew-test-bot.rb
Since 4673c507, Travis no longer performs a `brew pull`; however, the URL to pull from is still being set even though it will never be used.
> Remove leftover Travis code

- cmd/brew-test-bot.rb
The ?override=1 parameter is only needed to overwrite already published
artifacts. You can overwrite unpublished artifacts without it.
> Do not use ?override=1 when uploading to Bintray

- .travis.yml
This removes homebrew/core which causes `brew doctor` to retap it which is slow and error-prone.
> travis.yml: don't delete homebrew/* taps.

- cmd/brew-test-bot.rb
On Linux this defaults to Linuxbrew but in some cases (i.e. a Linux machine performing uploads for Homebrew) we want to allow this to be overridden back to the defaults.
Relies on https://github.com/Homebrew/brew/pull/2546.
> Force Homebrew GitHub organisation.

- cmd/brew-test-bot.rb
Bintray's API seems to lie and say things are published when they are not so (for now at least) go back to the old approach of assuming a `curl` failure means a file wasn't published.
> test-bot: fix Bintray published file check.

- cmd/brew-test-bot.rb
These directories are only ever needed at runtime and we're not running anything except the main formula. The way bottle etc/var handling works assumes a clean slate before `brew install` so this becomes considerably more reliable when we just delete everything.
Worst case this introduces some weird `brew test` failure in future that mean we can `brew postinstall` (which, as-of, Homebrew/brew#2579 will reinstall configuration files) on formulae as needed if we hit that.
> test-bot: nuke etc/var before installation.

- cmd/brew-test-bot.rb
Don't build a URL with a missing PR number. This may then error elsewhere depending on build type but that will be easier to understand.
> test-bot: handle a missing PR URL better.

- cmd/brew-test-bot.rb
Although it won't be distribute as a bottle this saves a bit of time by skipping post-install and by putting config files in `.bottle` where they can be globbed and removed by `test-bot`.
> test-bot: build devel as a bottle too.

- cmd/brew-test-bot.rb
This ends up breaking more than it fixes because then reverse dependencies are missing stuff they need.
> test-bot: stop unlinking non-dependencies.

- cmd/brew-test-bot.rb
Otherwise the formula path may be wrong. This is a better fix than https://github.com/Homebrew/brew/pull/2614
If you try to build a formula that depends on a formula from another tap, it may not build if the following is true:
* The other tap doesn't store formula in a `Formula/` folder
* The other tap was not yet tapped when test-bot is invoked
For example, while testing the `gazebo7` formula in https://github.com/osrf/homebrew-simulation/pull/240, I see the following console message when running `brew test-bot gazebo7` with `cartr/qt4` pre-tapped:
~~~
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader):
loading /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/qt@4.rb
~~~
It loads the formula successfully and isn't looking in the `Formula/` folder. If `cartr/qt4` is …
> Clear tap cache before tapping

- .travis.yml
While 1.15.0 is the latest Bundler and broken for us this cache seems to repeatedly poison itself so just remove it for now.
> travis.yml: remove gem cache.

- cmd/brew-test-bot.rb
Only run on cleanup but should avoid any long-running tests from staying alive beyond when they should.
While we're here also:
- test (rather than run directly) more Git commands
- make some Rubocop style fixes
> Kill still running processes

- cmd/brew-test-bot.rb
Make sure the current directory has any Git metadata cleaned up and don't bother to stash things.
> test-bot: tweak git cleanup.

- cmd/brew-test-bot.rb
It's safe to assume given everything else that we have an internet connection for the bot.
Closes https://github.com/Homebrew/brew/pull/2691.
> test-bot: run tests with --online.

- cmd/brew-test-bot.rb
If postinstall has not been run, some test blocks will fail. Unlike
stable, uninstalling and then pouring the devel bottle is not currently
an option because the mismatch between the bottle version and the
formula's stable version would trigger an exception. Just removing
--build-bottle for devel is also not an option since the .bottle
directory is needed for cleanup.
> test-bot: manually run postinstall for devel.

- .travis.yml
Let's see if it'll allow itself to be cached now.
> .travis.yml: try new Bundler 1.15.1.

- cmd/brew-test-bot.rb
This is needed both for `--ci-upload` and for `brew update-test` to not fail.
Also, while we're here, fix up some RuboCop failures.
> test-bot: set Git configuration name/email.

- cmd/brew-test-bot.rb
For example, skip a formula, rather than fail CI, if one of the
formula's dependencies has a minimum macOS requirement that's not
satisfied.
Issue Homebrew/brew#1247.
> test-bot: skip if req(s) of deps are unsatisifed

- cmd/brew-test-bot.rb
It's really slow to run these test suites three times on Travis' macOS workers but fast on their Linux ones. This should shave about 5m off our typical build time.
> test-bot: only run generic, no-compat on Linux.

- cmd/brew-test-bot.rb
For some reason they insist on using Ruby 2.4 with RVM which needs our `libyaml` formula installed. Without this: no build gem caching.
> test-bot: install libyaml on Travis.

- .travis.yml
- cmd/brew-test-bot.rb
Don't cleanup the kegs we need for cache upload to work but disable the bundler caching because it seems to explode.
> travis.yml: more cache changes.

- cmd/brew-test-bot.rb
This shouldn't be building from source when `--no-bottle` is passed but instead just omit the `--build-bottle`.
CC @ilovezfs
> test-bot: fix --no-bottle behaviour.

- .travis.yml
Change the umask before we create any files to avoid `brew audit` complaining about the `chmod` of formulae.
> travis.yml: fix umask for brew audit.

- cmd/brew-test-bot.rb
Reverts Homebrew/homebrew-test-bot#125 and attempts https://github.com/Homebrew/homebrew-test-bot/pull/124 once more. Will be fixed before it's merged.
> test-bot: make some style fixes.

- cmd/brew-test-bot.rb
Previously, only stable was able to rescue CompilerSelectionError and
install gcc automatically.
> test-bot: install gcc for devel and head if needed

- cmd/brew-test-bot.rb
This is going away in https://github.com/Homebrew/brew/pull/3661.
> test-bot: remove default formula support.

- .travis.yml
- cmd/brew-test-bot.rb
Port over the fixes from https://github.com/Homebrew/brew/pull/3736.
Additionally, don't untap Homebrew Cask (it wastes time for no benefit) and install `libgmp` for Travis CI build caching to work again.
> Make Travis CI tweaks and fixes

- cmd/brew-test-bot.rb
Use FormulaInstaller::expand_requirements in test-bot's
satisfied_requirements? function to ensure that
build requirements are ignored for formulae that
are poured from bottles.
Fixes #115.
This solution has the advantage of de-duplicating some code between `brew` and `test-bot`, but it's possible that the logic in `FormulaInstaller::expand_requirements` is supposed to differ from the test-bot `satisfied_requirements?` function. If so, then this may not be the preferred solution. Thanks for your time.
> Use FormulaInstaller logic for satisfied reqs

- cmd/brew-test-bot.rb
Otherwise unsatisfied build requirements are not skipped correctly.
CC @scpeters FYI
> test-bot: set build_bottle when expanding reqs.

- .travis.yml
- cmd/brew-test-bot.rb
Now https://github.com/Homebrew/brew/pull/3820 has been merged let's make sure both macOS and Linux are checking they haven't broken homebrew-core.
CC @sjackman FYI.
> Always run `brew readall` on homebrew-core.

- .travis.yml
- cmd/brew-test-bot.rb
This means the logic can be removed from `.travis.yml` files.
> Clone homebrew/core automatically when not present

- cmd/brew-test-bot.rb
Otherwise the `brew test` of these reverse dependencies will fail.
> test-bot: install missing bottle test deps.

- cmd/brew-test-bot.rb
Now that this fills in missing dependencies it’s more useful to us.
> test-bot: use more only-dependencies.

- cmd/brew-test-bot.rb
If `--root-url` is passed, use the specified URL as the root of the bottle's URL instead of Homebrew's default.
> Add option --root-url

- cmd/brew-test-bot.rb
If `--or-later` is passed, append `_or_later` to the bottle tag.
> Add option --or-later

- cmd/brew-test-bot.rb
Avoid strange broken opt symlink errors on some `brew doctor` runs other
than the first.
> test-bot: only run setup once

- cmd/brew-test-bot.rb
Fixes:
```
Error: undefined local variable or method `formula_name' for #<Homebrew::Test:0x00000002fb7000>
Did you mean?  formulae
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:657:in `rescue in install_gcc_if_needed'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:635:in `install_gcc_if_needed'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:889:in `formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:1283:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot/cmd/brew-test-bot.rb:1282:in `each' …
```
> brew-test-bot: use formula.name

- .travis.yml
Otherwise `brew help` will try to install an old portable Ruby.
> .travis.yml: reset HOMEBREW_REPOSITORY on macOS.

- cmd/brew-test-bot.rb
Needed for https://github.com/Homebrew/brew/pull/4195.
> Skip untapping `homebrew/cask`.

- Formula/testbottest.rb
This adds a bottle block to satisfy the `audit --online` step of the travis `brew` tests.
https://github.com/Homebrew/brew/pull/4420
> testbottest: add bottle block

- Formula/testbottest.rb
Apologies, this doesn't actually work. Reverting in favour of exempting the `testbottest` formula from the bottle audit in https://github.com/Homebrew/brew/pull/4420.
> Revert "testbottest: add bottle block"

- cmd/brew-test-bot.rb
Depends on https://github.com/Homebrew/brew/pull/4569.
> `curl_args` does not include `curl_executable` anymore.

- cmd/brew-test-bot.rb
There was an expectation https://github.com/Homebrew/homebrew-core/pull/31382 should be red-flagged by CI because that formula is currently a mandatory dependency, albeit at buildtime, of `elm` and consequently removing it would break `elm`, but instead CI failed to provide any warning about consequences of removing it.
> brew-test-bot: check build/optional for deleted formulae

- cmd/brew-test-bot.rb
This ensures they have the right permissions and `brew doctor` doesn't
get upset.
> test-bot: create necessary top-level directories.

- cmd/brew-test-bot.rb
The previous approach still seemed to be failing at `brew doctor` time.
> cmd/brew-test-bot: try harder to install git.

- azure-pipelines.yml
- cmd/brew-test-bot.rb
This avoids it being removed by a `git clean`.
> Copy coverage data into root.

- cmd/brew-test-bot.rb
- Run `brew man` and `brew style` after `brew tests` because they use the gems installed by `brew tests`.
> Adjust configuration based on Homebrew/brew changes

- cmd/brew-test-bot.rb
Iterates on https://github.com/Homebrew/homebrew-test-bot/pull/193.
Will be unnecessary as-of https://github.com/Homebrew/homebrew-test-bot/pull/192.
> test-bot: don't remove lib/pkg-config.

- cmd/brew-test-bot.rb
This is necessary for https://github.com/Homebrew/brew/pull/4970 and should not be required after https://github.com/Homebrew/homebrew-test-bot/pull/192.
> test-bot: don't remove var/homebrew/linked.

- .travis.yml
- cmd/brew-test-bot.rb
This saves having Homebrew do it or `brew doctor` complaining.
This will not be necessary after https://github.com/Homebrew/homebrew-test-bot/pull/192 is merged.
> test-bot: create cellar.

- cmd/brew-test-bot.rb
> test-bot: fix cleanup on Homebrew/brew.

- cmd/brew-test-bot.rb
Use `tap.default_remote` for pull requests.
CC @sjackman
> brew-test-bot: use tap.default_remote for pull requests

- azure-pipelines.yml
This avoids having to manually remove `homebrew-cask` as `test-bot` will do it and speeds up the build by only fetching Homebrew/brew.
> azure-pipelines: use update-reset arguments.

- .travis.yml
We have Azure Pipelines doing Linux builds for us now. They also do macOS builds but CodeCov doesn't work there (yet).
> travis: only build on macOS.

- .travis.yml
- azure-pipelines.yml
- cmd/brew-test-bot.rb
This will allow coverage submission to be moved to Azure (which is quicker).
> test-bot: require COVERALLS_REPO_TOKEN.

- cmd/brew-test-bot.rb
This is no longer needed after https://github.com/Homebrew/brew/pull/5467 has been merged.
> test-bot: remove brew prune.

- cmd/brew-test-bot.rb
This is being done in https://github.com/Homebrew/brew/pull/5549 instead.
> test-bot: remove manual CI=1 assignment.

- cmd/brew-test-bot.rb
These are useful in debugging e.g. #231.
> test-bot: don't hide build bottle/from source args.

- cmd/brew-test-bot.rb
Imported from Linuxbrew/homebrew-test-bot.
Mentioned in https://github.com/Homebrew/homebrew-test-bot/pull/236#issuecomment-463361871
> test-bot: add required Linuxbrew taps.

- cmd/brew-test-bot.rb
https://github.com/Homebrew/brew/pull/5762 deprecates some ARGV methods, this PR removes calls to the deprecated methods so that brew test-bot won't fail
> Remove calls to deprecated ARGV methods

- cmd/brew-test-bot.rb
Reverts Homebrew/homebrew-test-bot#238
@BenMusch @jonchang Unfortunately #238 wasn't quite correct; it broke verbose output due to `ARGV` being modified after the fact: https://github.com/Homebrew/homebrew-test-bot/blob/232733283f2e55c0a2b50dbd2dd784344b6d02ed/cmd/brew-test-bot.rb#L1555-L1581
I would suggest making use of `ARGV.freeze` to catch these cases (both here and in Homebrew/brew) and fix/refactor them before any more `ARGV` to `Homebrew.args` conversion is done.
Sorry! ❤️
> Revert "Remove calls to deprecated ARGV methods"

- cmd/brew-test-bot.rb
macOS is preferable for these and Azure Pipelines doesn't have the massively slower macOS builds Travis CI had.
> test-bot: run generic/no-compat tests on macOS.

- cmd/brew-test-bot.rb
Sets `HOMEBREW_RELOCATE_METAVARS`, which instructs keg relocation on macOS to collapse all `@rpath`-prefixed install names and delete all `LC_RPATH`s from all binaries, if possible.
See https://github.com/Homebrew/brew/pull/5413
cc @sjackman
> brew-test-bot: Enable RPATH rewriting during tests

- cmd/brew-test-bot.rb
This reverts commit 30ba31514b4299735582b339cd99262bd8ed208f.
cc @scpeters
> Revert "brew-test-bot: Enable RPATH rewriting during tests"

- cmd/brew-test-bot.rb
This isn't used yet but will be used shortly to test frozen literals before we enable this for Homebrew developers (then Homebrew users).
> test-bot: set HOMEBREW_FROZEN_STRING_LITERAL.

- cmd/brew-test-bot.rb
Changing the approach in https://github.com/Homebrew/brew/pull/6036 as we cannot use `--frozen-string-literal` for now due to https://bugs.ruby-lang.org/issues/12031.
Reverts Homebrew/homebrew-test-bot#247
> Revert "test-bot: set HOMEBREW_FROZEN_STRING_LITERAL."

- cmd/brew-test-bot.rb
Hi there! 
This PR adds `ENV["HOMEBREW_NO_COLOR"] = "1"` for Azure Pipeline.
Without it, the color output is broken by `<` & `>` as explained here: https://github.com/Microsoft/azure-pipelines-agent/issues/1569#issuecomment-447497620
**Live preview**
**Detailed output view**
Might be better to turn it off while waiting for a fix from Azure.
Best,  
-- Ladislas
> add HOMEBREW_NO_COLOR for Azure Pipeline

- cmd/brew-test-bot.rb
Hi there!
As explained [here](https://discourse.brew.sh/t/tap-bottles-how-to-publish-after-ci-upload-to-bintray/4674), `brew test-bot --ci-upload` was pushing the changes to `master` which would then break the use of `brew pull --bottle`.
In this PR, I've removed the push of the changes to `master` but I've kept the push of the `tag`, which fixes the issue.
**BUT**, maybe this behavior is needed for your CI/CD, so the same behavior could be achieved by adding an option such as `--no-pushToMaster` or an `ENV["HOMEBREW_NO_PUSH_TO_MASTER"]`.
Let me know what you think!
Best,  
-- Ladislas
> brew test-bot --ci-upload - Push only tags to remote

- cmd/brew-test-bot.rb
On Azure, the "magic" was not happening (https://github.com/Homebrew/homebrew-test-bot/issues/251#issuecomment-486345482).
This PR fixes the issue and add a comment about `git checkout $(System.PullRequest.SourceBranch)` before calling `brew test-bot`.
> Fix detection of modified formulae on Azure

- cmd/brew-test-bot.rb
`brew uninstall` has no option `--devel`.
> Fix uninstall: Error: invalid option: --devel

- cmd/brew-test-bot.rb
If there's an ongoing (or, more likely, failed) `rebase` or `am` in Homebrew/homebrew-core then make sure it's cleaned up accordingly.
> test-bot: abort more core operations.

- cmd/brew-test-bot.rb
Reverts Homebrew/homebrew-test-bot#264
It didn't fix the problem.
> Revert "test-bot: abort more core operations."

- cmd/brew-test-bot.rb
Otherwise they may attempt to pour from bottles and fail.
Fixes #266.
> test-bot: don't uninstall installed formula.

- cmd/brew-test-bot.rb
Will catch the case that's kept biting us with `rubocop-performance`.
> test-bot: check for uncommitted gems.

- cmd/brew-test-bot.rb
- There are some _large_ formulae with many dependencies. One of these
is `bzip2`. In those cases, we don't want to test all of its dependencies
in one go because it times out on CI. We especially don't want to test
all of its _recursive_ dependencies, as there are _lots_.
- We can perform manual tests of some formulae to ensure that we're
keeping functionality, if the formuale that's depended on has made
breaking changes to its libraries with its upgrade.
> brew-test-bot: Add a `--skip-recursive-dependents` flag

- cmd/brew-test-bot.rb
The result of this call to brew uses --recursive is ignored.
> Remove the call to brew uses --recursive

- azure-pipelines.yml
Our main CI is now on GitHub Actions so just test on Linux (and not build a Docker image) to avoid regressions on Azure Pipelines.
> azure-pipelines: only build on Linux.

- cmd/brew-test-bot.rb
Looks like colorized text is showing up just fine on Github Actions:
https://github.com/dawidd6/homebrew-test/commit/585717b67f9eda62a79c69e699f50b21fff9b397/checks
I think it's worth it to make this change.
> Use color in Github Actions

- cmd/brew-test-bot.rb
This change is mostly needed on linux. Tapping `linuxbrew/xorg` is required for some formulas and it is not done when `brew test-bot` is run with `--tap` option specified.
I didn't really give this change a test run, but if I understand the code well, it should do the job and prevent situations like this one:
https://github.com/dawidd6/homebrew-tap/commit/d6f07e80d6178260e28870f93a24a68c8cf8e43a/checks
where whole build fails because of this:
```
==> brew linkage --test dawidd6/tap/neofetch
Error: No available formula with the name "linuxbrew/xorg/xorg" 
Please tap it and then try again: brew tap linuxbrew/xorg
==> FAILED
```
and manual tapping of `linuxbrew/xorg` before build seems to fix it:
https://github.com/dawidd6/homebrew-tap/commit/4d549e4e54c34da15a142de64506888dc1d77b9e/checks
> Tap REQUIRED_TAPS when --tap option is specified

- cmd/brew-test-bot.rb
Ensure that we're not accepting a Mojave bottle on Catalina when testing bottled dependents. Furthermore, don't test bottled dependents at all for `--keep-old` jobs; it slows things down hugely for no benefit.
> test-bot: fix bottled dependents testing.

- cmd/brew-test-bot.rb
We don't need this as run on other OSs anyway and this workaround is cleaner at this point than trying to hack around it.
> test-bot: don't run gem stuff on Mojave.

- cmd/brew-test-bot.rb
This should ensure that we don't e.g. update `go` or `ghc` where most dependents are `:build` and break those formulae building from source.
As requested by @fxcoudert.
> test-bot: check build dependents.

- .github/workflows/tests.yml
Remove GitHub Actions default 2.6 RubyGems which cause the macOS build to explode.
> test-bot: fix broken macOS build.

- lib/test.rb
Revert #295.
We do not have enough CI power right now to test all such formulas (although we should in principle).
This is making life difficult right now for python formulas.
> Do not check build dependents (revert #295)

- lib/test.rb
Expand on https://github.com/Homebrew/homebrew-test-bot/pull/306 to do further cleanup during the build (CC @Bo98 @fxcoudert).
There's no real need to keep these around; they can be reinstalled from bottles when needed and they just take up a lot of disk space.
In comparison, the `modified_formulae` need to stick around because they cannot be reinstalled from bottles after being uninstalled.
> lib/test: uninstall bottled dependents.

- lib/test.rb
Fixes https://github.com/Homebrew/homebrew-test-bot/issues/301
> lib/test: remove non-existent OSXFuse symlinks.

- lib/test.rb
- spec/test_spec.rb
If needed a longer hash can be used. Fixes detection of `abcde`.
> lib/test: prioritise formula names over commit hashes.

- lib/test.rb
Set environment variable to run `sudo purge` a few times to potentially work around https://github.com/Homebrew/brew/issues/6539.
Depends on https://github.com/Homebrew/brew/pull/6931 (and my setting up `sudo purge` to run without a password on our Catalina CI nodes).
> test: set HOMEBREW_BOTTLE_SUDO_PURGE.

- cmd/brew-test-bot.rb
- lib/test_bot.rb
If `--publish` is passed, publish the uploaded bottles.
> Add option brew test-bot --ci-upload --publish

- lib/test.rb
After building a bottle, `brew test-bot` tries to install (bottled) dependents but does not use fully-qualified formulae names (`org/repo/formula`). It causes `test-bot` to fail in certain situations (example: https://github.com/Linuxbrew/homebrew-xorg/pull/607) despite successfully building a bottle for the changed formula.
Looking at `lib/test.rb`, I suspect that the function at fault is `install_bottled_dependent`. This function is called in a loop (lines 704-706):
```
@bottled_dependents.each do |dependent|
install_bottled_dependent(dependent)
end
```
`bottled_dependents` is, in turn, a list of dependents that have bottles. I believe that the change I propose here will address the issue I'm seeing in the PR referenced above.
> test.rb: use fully-qualified names for dependents

- lib/test_bot.rb
This should avoid them having to be set manually on the machines (or by the CI provider).
> test_bot: set Git variables for `brew pull`

- lib/test.rb
In #311, the check for arguments matching a safe formula canonical name was increased in priority. It is currently checked before matching against the `HOMEBREW_PULL_OR_COMMIT_URL_REGEX` (defined in [brew global.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/global.rb#L105-L106)), which [causes URL's to be passed to `Formulary.factory()`](https://github.com/Homebrew/homebrew-test-bot/blob/master/lib/test.rb#L63-L64) and spam the console with complaints about how the html in that page is not a valid formula. For example from [a recent build of mine](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/label=osx_mojave/651/console):
~~~
+ brew test-bot --tap=osrf/simulation --root-url=https://osrf-distributions.s3.amazonaws.com/bottles-simulation …
> lib/test: prioritise urls over formula names

- lib/test.rb
We no longer use this workflow in Homebrew/linuxbrew-core, so remove this special-cased merge commit logic to simplify for our current practices.
> Remove the magic merge commit logic

- cmd/test-bot.rb
Retry `curl` commands three times to reduce the chance of intermittent network issues causing CI to fail.
> Add `HOMEBREW_CURL_RETRIES` to make downloads/audit more robust.

- lib/test.rb
Reverts Homebrew/homebrew-test-bot#334
This is going to break the case where you have multiple changed formula in a PR that interact (e.g. one depends on another).
> Revert "test-bot: uninstall tested formula at the end"

- lib/test_bot.rb
When building formulae, brewed curl may be in the path.
To be sure we are always using system curl, which is known to work,
we hardcode that path everywhere, as we did for git.
> test-bot: use system curl everywhere

- lib/test.rb
We do this already when installing dependents from bottles: https://github.com/Homebrew/homebrew-test-bot/blob/3dc6ea64d4783be1c653bb0893acaa0fd6473e8e/lib/test.rb#L756-L759
Here's a scenario where we need it (see Homebrew/homebrew-core#51255):
* ocaml is updated, along side a revision bump for ocaml-num
* ocaml is tested first and with that, dependents are installed from source
* compcert is tried first, which has ocaml-num as a dependency
* ocaml-num is installed (via `brew install --only-dependencies`) and isn't explicitly marked as to be installed from source at this point, so an install from a bottle is attempted
* This, of course, fails (no bottle exists yet for that revision), but instead of going on to install from source, it aborts due to …
> test: unset HOMEBREW_DEVELOPER when building dependents from source

- cmd/test-bot.rb
- lib/test.rb
* self hosted runners need all of `cleanup_after` since the VMs are not ephemeral
* self hosted runners should modify $HOME to the runner working directory to avoid polluting the VM home directory
See https://github.com/Homebrew/homebrew-core/pull/50620 for how this affects self-hosted runners on actions.
> Add logic to handle self-hosted runners

- lib/test.rb
Should prevent situations like this (on Linux):
```
==> brew fetch --retry netpbm --build-bottle --force
==> Cloning https://svn.code.sf.net/p/netpbm/code/stable
==> Checking out 3750
You must: brew install svn
==> Retrying download
==> Cloning https://svn.code.sf.net/p/netpbm/code/stable
==> Checking out 3750
You must: brew install svn
Error: Failed to download resource "netpbm"
Failure while executing; `svn checkout https://svn.code.sf.net/p/netpbm/code/stable /github/home/.cache/Homebrew/netpbm--svn --quiet -r 3750` exited with 1. Here's the output:
You must: brew install svn
==> FAILED
```
https://github.com/Homebrew/linuxbrew-core/pull/19893/checks?check_run_id=518562926
> test: install subversion if needed

- lib/test.rb
Request of https://github.com/Homebrew/homebrew-core/pull/51883#issuecomment-601579482
This pull request will build formulae that depend on `openjdk` from source on test-bot runs.
> test: build openjdk dependents from source

- cmd/test-bot.rb
Reverts Homebrew/homebrew-test-bot#327.
Depends on https://github.com/Homebrew/brew/pull/7196.
> Revert "Add `HOMEBREW_CURL_RETRIES` to make downloads/audit more robust."

- lib/test_bot.rb
We are unable to use `brew test-bot --ci-upload --publish` during the CI transition period from Jenkins to GitHub Actions.
Here I upload (but not publish) three files to Bintray.
```console
% curl --upload-file actual.tar.gz https://api.bintray.com/content/homebrew/bottles/mednafen/1.24.1/mednafen-1.24.1.catalina.bottle.tar.gz
HTTP/1.1 201 Created
{"message":"success"}
% curl --upload-file actual.tar.gz https://api.bintray.com/content/homebrew/bottles/mednafen/1.24.1/mednafen-1.24.1.mojave.bottle.tar.gz
HTTP/1.1 201 Created
{"message":"success"}
% curl --upload-file actual.tar.gz https://api.bintray.com/content/homebrew/bottles/mednafen/1.24.1/mednafen-1.24.1.high_sierra.bottle.tar.gz
HTTP/1.1 201 Created
{"message":"success"}
```
Now I wish to upload a (possibly different) file and …
> test-bot: use separate API call on publish

- lib/test.rb
I had hoped to get this before Homebrew/homebrew-core#51747 was merged, so let's at least try to get this in before the subsequent fixup pull requests are also merged, and restart any already-run CI jobs as needed.
> test: add docbook-xsl to BFS whitelist

- lib/test.rb
Currently, it is possible that we build things twice. For example, if `ocaml` and `ocaml-findlib` are both modified in the same pull request, the sequence may be somehing like:
* Build `ocaml`.
* Test `ocaml` dependents, some of which will also depend on `ocaml-findlib`.
- `ocaml-findlib` will be built by the `brew install --only-dependencies` step.
* `ocaml-findlib` is uninstalled and built once again, except with `--build-bottle` this time.
* Test `ocaml-findlib` dependents (which is just a subset of the `ocaml` dependents)
- In this case there are no runtime dependencies, but there will be some duplication here for other formulae.
I initially saw this as just a build time inefficiency, but it turns out that this process has a serious effect on the bottles we produce: …
> test: avoid building formulae twice

- lib/test_bot.rb
This prevents erroneous bottle publication when we are merely seeing what commands will be run.
> test-bot: teach --publish to obey --dry-run

- lib/test.rb
Part of https://github.com/Homebrew/brew/issues/7029.
This will allow us to make deprecated/disabled formulae not cause CI issues.
Requires https://github.com/Homebrew/brew/pull/7190 to be merged to work.
> lib/test: skip disabled/deprecated formula.

- lib/test.rb
This was just run on Homebrew/brew otherwise.
CC @jonchang this is why your `brew style` violation didn't show up.
> test: run brew style on correct tap.

- .github/workflows/tests.yml
- Gemfile
- Gemfile.lock
- cmd/test-bot.rb
- lib/step.rb
- lib/test.rb
- lib/test_bot.rb
- spec/spec_helper.rb
Now that we've decommissioned jenkins.brew.sh we can delete all Jenkins related code. While doing this, audit remaining code to ensure that all methods, parameters, environment variables and configurations are those used and supported by Homebrew.
> Delete unused code.

- lib/step.rb
ActiveSupport can barf on some Unicode.
> step: use output.empty?

- lib/step.rb
- lib/test.rb
- spec/homebrew/step_spec.rb
Cleanup all use of parameters and instance variables to keep data more closely scoped to existing functions (where possible).
This will enable future PRs to split up the `test-bot` output.
> test-bot: cleanup parameters, variables.

- lib/test_bot.rb
At the end of the output have a summary of all the steps that have failed. This can be output by GitHub Actions as a quicker summary.
> test_bot: failed steps summary.

- lib/test.rb
This will have already been set (possibly to a different value).
> lib/test: don't (re)set diff_start_sha1 for URLs.

- lib/test.rb
These aren't substantially more readable and they make all comparison operations incorrect.
> lib/test: no short SHA-1s.

- cmd/test-bot.rb
- lib/test.rb
This simplifies some logic so later we can assume `--no-pull` when running a single (non-download) step.
> test_bot: don't checkout on `brew pull`

- .github/workflows/tests.yml
- cmd/test-bot.rb
- lib/test.rb
- lib/test_bot.rb
Accept only formula, `HEAD` or GitHub Actions commits for building.
I believe other functionality is unused. If I'm wrong: correct me.
> test_bot: restrict CLI arguments.

- cmd/test-bot.rb
- lib/step.rb
- lib/test.rb
- lib/test_bot.rb
- spec/homebrew/step_spec.rb
- spec/stub/utils.rb
- Don't pass `--verbose` by default with GitHub Actions (instead, just output failed steps)
- Always output `brew config` even when it doesn't fail (as it almost never does).
- Don't run `brew --env` as we don't really care about the output.
- Output repository revisions with a headline and after they won't change again.
- More consistent spacing and colours.
> Make GitHub Actions output less verbose

- .github/workflows/tests.yml
- cmd/test-bot.rb
- lib/test.rb
This will allow the test-bot logs to be more segmented in GitHub Actions and avoid wasting time testing some formulae when others have invalid syntax.
> Provide arguments to only test one step.

- lib/test_bot.rb
- lib/test_runner.rb
Further slim down `lib/test_bot.rb`.
This will also allow splitting up/moving around `lib/test.rb` logic.
> Extract TestRunner module

- lib/test_runner.rb
- lib/tests/tap_syntax.rb
This will allow the creation of more Test subclasses that don't share methods and are correctly invoked by TestRunner.
> Build multiple Test objects.

- lib/tests/formulae.rb
Otherwise it can return e.g. `origin/master` if it cannot find it.
> formulae: make rev-parse only return revisions.

- .github/workflows/tests.yml
* `HOMEBREW_PREFIX` is used but was not defined if brew is pre-installed.
* Pre-installed Linuxbrew is also now at the end of the path - we want it at the beginning to prevent a `brew doctor` error.
> workflows/tests: fix for pre-installed Linuxbrew

- lib/tests/formulae.rb
This PR adds erlang to build-from-source whitelist. This should help to catch build problems on erlang-dependant formulae earlier and help to decide if we need to add a versioned formula for the previous version (in case of major updates).
> tests/formulae: add erlang to BFS whitelist

- README.md
Noticed the README as-is was wrong.
> README: clarify CI providers.

- lib/tests/cleanup_before.rb
This should make debugging more obvious.
> cleanup_before: clarify when testing Homebrew/brew.

- lib/test_bot.rb
This avoids having to specify `--tap`.
> test_bot: automatically detect linuxbrew-core.

- lib/tests/formulae.rb
Error message encountered:
> ==> brew fetch --retry freerdp
Error: Calling Formula#installed? is deprecated! Use Formula#latest_version_installed? (or Formula#any_version_installed? ) instead.
Please report this issue to the homebrew/test-bot tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:408
Source:
https://github.com/Linuxbrew/homebrew-xorg/pull/645/checks?check_run_id=702425713#step:6:39
I believe `any_version_installed?` is more appropriate than `latest_version_installed?`.
> lib/tests/formulae.rb:408: Use `any_version_installed?` instead of `installed?`

- lib/tests/formulae.rb
Same as #410 but for line 395
Failed log: 
https://github.com/Linuxbrew/homebrew-xorg/pull/645/checks?check_run_id=702574635#step:6:73
> lib/tests/formulae.rb:395: Use any_version_installed? instead of installed?

- README.md
- cmd/test-bot.rb
This is included in `brew man`, `brew test-bot --help` and is less likely to get outdated as a result.
> README: move documentation to --help.

- lib/tests/formulae.rb
As `downloads` wasn't being cleaned appropriately the previous way.
> formulae: use more aggressive cache removal.

- lib/tests/formulae.rb
Similar to #117, rescue from TapFormulaUnavailableError while checking the recursive dependencies of formula dependents.
This popped up because the osrf/simulation tap that I maintain has an old but LTS formula (`gazebo7`) that [depends on `cartr/qt4/qt@4`](https://github.com/osrf/homebrew-simulation/blob/master/Formula/gazebo7.rb#L14), and when I try to build one of its dependencies hosted in that tap (`ogre1.9`), `test-bot` [fails with](https://build.osrfoundation.org/job/generic-release-homebrew_bottle_builder/867/label=osx_mojave/console):
~~~
Error: No available formula with the name "cartr/qt4/qt@4" 
Please tap it and then try again: brew tap cartr/qt4
~~~
I traced it to `lib/tests/formulae.rb:349` in local testing with `--debug` and `--verbose`. Rescuing from …
> Check for untapped deps of dependents

- README.md
Anywhere we can use `blob/master` we can use `blob/HEAD` instead. This will make life easier if we ever rename our default branch in future (once/if Git and GitHub provides the necessary tooling to do so).
> Refer to default branch in links with HEAD

- lib/tests/setup.rb
This should avoid `brew doctor` failures due to not-yet installed gems on self-hosted runners.
> lib/tests/setup: install bundler gems.

- lib/test_cleanup.rb
- lib/tests/cleanup_after.rb
This means it'll be run both before and after builds.
> Move `brew cleanup` to `cleanup_shared`.

- Formula/testbottest.rb
- LICENSE.txt
This updates the license to match the license wording for the other Homebrew repositories (eg brew, homebrew-core) in a way that GitHub will detect it.
> Update License wording

- lib/tests/formulae.rb
* Only pass `--skip-style` for existing formulae, otherwise strict style checks will never be run (they should be for new formulae).
* Always pass `--online`, otherwise things like the license will not be validated for new formulae.
> lib/tests/formulae: adjust audit args

- lib/test.rb
- lib/tests/cleanup_after.rb
- lib/tests/cleanup_before.rb
- lib/tests/formulae.rb
We don't want special logic for this tap any more (and it's not reliable
with e.g. Docker). Also allow `testbottest` to be tested purely based
on the argument being passed rather than needing the right tap.
> Cleanup test_bot_tap logic.

- lib/tests/formulae.rb
- when testing a formula as a dependent of another: retry the test on failures (requires https://github.com/Homebrew/brew/pull/8135)
- when testing a added/modified formula:
- don't retry the test (we want to know if it's flaky)
- don't try to test dependents if the test fails
This should improve both the reliability and performance of PRs with large numbers of dependents.
> formulae: adjust testing behaviour.

- lib/tests/formulae.rb
This was implied by the variable name but omitted by mistake.
> formulae: test dependents where formula has missing test.

- .github/workflows/tests.yml
- lib/tests/formulae.rb
- lib/tests/tap_syntax.rb
We need to get on top of our failing CI problems. This will block us doing dependent testing or shipping bottles for formulae where linkage or tests fail on the changed formula. We will still allow this on dependent formulae.
Also, run `brew audit` without Git, style (RuboCop) or online checks in the tap syntax checking step. This is fast enough now (takes under a minute on my machine) and these are the audit failures we should never accept failures on.
Needs https://github.com/Homebrew/homebrew-core/pull/58905
CC @homebrew/core for thoughts
> Don't test dependents on audit/linkage/test failure.

- lib/test.rb
- lib/test_cleanup.rb
- lib/test_runner.rb
- lib/tests/cleanup_after.rb
- lib/tests/cleanup_before.rb
- lib/tests/formulae.rb
- lib/tests/setup.rb
- lib/tests/tap_syntax.rb
I personally found this call very confusing:
```rb
test "command", "arg1", "arg2", args: args
```
I've tried to refactor that away by instead passing the needed dry run and fail fast args to the Test class `initialize` method, store it there and reference that in the `test` method.
> Refactor dry run & fail fast handling

- lib/tests/formulae.rb
Otherwise, `rm -rf` will fail when deleting `go_mod_cache`.
> lib/tests/formulae: set permissions in cleanup_during!

- lib/test.rb
- lib/test_cleanup.rb
- lib/tests/cleanup_before.rb
- lib/tests/formulae.rb
Things like purging the prefix isn't the quickest task in the world. But because it doesn't go through the `test` method, there's no indication that is what is currently happening - it just appears that it's still doing `git clean` or something.
For tasks like this, and depenency/dependent searching, it's worthwhile to print something that indicates what is happening.
> More feedback on some slower non-test tasks

- .github/workflows/tests.yml
- lib/test_bot.rb
- lib/tests/formulae.rb
- Raise an exception if we haven't specified any formulae or found any to test (as that would be a no-op which almost always signals an error).
- use `UsageError`s rather than `odie` to get `--help` output
> Improve errors

- lib/tests/formulae.rb
It might not be worth spending time resolving audit failures of deprecated formulae, so don't have `test-bot` audit them.
Motivated by https://github.com/Homebrew/homebrew-core/pull/59071.
> formulae: don't audit deprecated formulae

- .github/workflows/tests.yml
- lib/tests/cleanup_before.rb
- lib/tests/tap_syntax.rb
- use Homebrew/actions/setup-homebrew
- do dry-run tests on Linux too
- move some GitHub Actions cleanup logic to cleanup_before
- only run `brew audit` in `tap_syntax` if there's formula files
> Better support and use Homebrew actions

- lib/test_cleanup.rb
These are all taps that will do no harm to be tapped (and we want to use them in Homebrew/brew CI).
> test_cleanup: allow (but don't require) some taps.

- lib/tests/formulae.rb
Allow this to pass as long as the start/end SHAs are different (as this indicates that we've got these values correctly from GitHub Actions).
Fixing issue seen in https://github.com/Homebrew/homebrew-core/pull/59205/checks?check_run_id=953231796#step:5:30
> formulae: loosen "no formulae" failure.

- lib/test_bot.rb
- lib/tests/cleanup_before.rb
- lib/tests/formulae.rb
This is useful when `test-bot` is run in multiple steps to ensure that these are always correct.
> Always output core and tap revisions.

- lib/tests/formulae.rb
Jobs in `homebrew-core` are currently failing, this PR _might_ fix it.
Example: https://github.com/Homebrew/homebrew-core/runs/957201337?check_suite_focus=true#step:5:21
> formulae: popen_read for git merge-base

- lib/tests/formulae.rb
This updates some commands that aren't already using full names, which fixes an issue with bottling of having a formula that has the same name as a core formula
> formulae: use full names

- lib/tests/formulae.rb
This should hopefully fix the recent CI failures on master: https://github.com/Homebrew/homebrew-test-bot/actions?query=event%3Apush
This change should also now allow branch names other than `master`.
> lib/tests/formulae: fetch ref on push events

- lib/tests/formulae.rb
Currently when bumping linux-only formulae in linuxbrew-core, reverse dependencies aren't tested because we `--keep-old`. This is undesired as formulae updates could cause breakage of the other formulae that depend on it.
This PR changes that.
> formulae: test reverse-deps of linux-only formulae

- lib/tests/formulae.rb
Homebrew/homebrew-core/pull/60943 is currently failing as `livecheck` has not been added for the formula
> formulae: run livecheck only if formula is livecheckable

- lib/test_ci_upload.rb
- lib/tests/formulae.rb
If not testing core tap (and a bunch of other conditions), set the root_url to GitHub releases url.
This url would later be used in `brew pr-upload` to determine what release to create.
> formulae: set root_url to GitHub Releases url

- lib/tests/formulae.rb
Apparently `tap` can be undefined.
```
==> Running Formulae#formula!(testbottest)
==> Determining dependencies...
==> Determining dependents...
==> Starting build of testbottest
==> brew fetch --retry testbottest --build-bottle --force
==> brew install --only-dependencies --verbose --build-bottle testbottest
==> brew install --verbose --build-bottle testbottest
==> brew audit testbottest --online --git --skip-style
Error: undefined method `core_tap?' for nil:NilClass
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:420:in `bottle_reinstall_formula'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:630:in `formula!'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae.rb:20:in `block in run!' …
```
> formulae: fix when tap is nil

- lib/test_bot.rb
Tap specified in `--tap=` was ignored due to typo.
> Fix name of tap argument

- lib/tests/cleanup_before.rb
GitHub has requested we request our usage of shallow clones. As a result stop doing shallow clones or fetches of homebrew-core.
> cleanup_before: don't use shallow clones/fetches.

- lib/tests/cleanup_before.rb
The Homebrew/setup-homebrew GitHub Action does this for us (in a more reliable fashion).
> cleanup_before: don't fetch homebrew-core.

- Formula/testbottest.rb
This will be deprecated in https://github.com/Homebrew/brew/pull/9209
> testbottest: remove :java.

- lib/tests/formulae.rb
Use Ruby patchelf to pour bottles, but not to build bottles. Set `HOMEBREW_NO_PATCHELF_RB_WRITE` unless `HOMEBREW_PATCHELF_RB_WRITE` is set.
> brew bottle: Set HOMEBREW_NO_PATCHELF_RB_WRITE

- lib/test_cleanup.rb
Should speed up `Homebrew/brew` tests a little.
> Don't untap `homebrew/cask-versions`.

- lib/test_cleanup.rb
- lib/tests/cleanup_before.rb
- output some debugging output to be able to identify which cleanup operations are (and are not) being performed for
https://github.com/Homebrew/homebrew-core/issues/66328
- don't try to "purge" anything if `brew --prefix` == `brew --repo` but do try to `git clean` in that case.
- remove logic for handling Git on old macOS versions.
> cleanup: various cleanup/fixes.

- lib/tests/formulae.rb
Only include formula dependents when determining which formulae to test. This solves the problems we've seen in https://github.com/Homebrew/homebrew-core/pull/66268 and https://github.com/Homebrew/homebrew-core/pull/66287.
This can't be merged until https://github.com/Homebrew/brew/pull/9437 is merged (which is what adds the `--formula` and `--cask` args to `brew uses`
> Exclude casks when determining dependants

- cmd/test-bot.rb
- lib/tests/formulae.rb
This is a workaround to allow building everything from source but not attempting to build bottles.
> test-bot: add --build-from-source.

- lib/tests/formulae.rb
If `HOMEBREW_REQUIRE_BOTTLED_ARM` is set then don't build a given formula and just skip it. This allows Homebrew/core to prevent ARM bottles from regressing or not being updated while allowing new bottles from being built/tested in the dispatch workflow.
> Add HOMEBREW_REQUIRE_BOTTLED_ARM temporary environment variable

- lib/test_runner.rb
"1 failed **steps**" is incorrect and should be "1 failed **step**"
> test_runner: pluralize "step"

- lib/tests/formulae.rb
This would allow us to create artifacts of failed bottles that can't be accidentally published; i.e. successful bottles would be uploaded to the `bottles` artifact, while failed bottles could be uploaded to a `bottles (failed)` artifact
Closes #559.
> Move bottle to subdirectory if linkage or test failed

- lib/test_cleanup.rb
- lib/tests/cleanup_before.rb
- move instead of deleting taps and node includes (when sensible)
- don't run `brew cleanup` unless self-hosted
> cleanup: speedup cleanup on GitHub Actions.

- lib/tests/formulae.rb
This should revert this commit: https://github.com/Homebrew/homebrew-test-bot/pull/525#issuecomment-769695114 which disabled our Ruby implementation of `patchelf` when building in CI.  Now that we are confident this is working correctly correctly, we can allow the Ruby `patchelf` to be used in CI as well.
> brew bottle: remove HOMEBREW_NO_PATCHELF_RB_WRITE

- lib/tests/formulae.rb
Fixes https://github.com/Homebrew/brew/issues/10498.
I opted for a `File.directory?` check instead of `mkdir_p` since it seemed more transparent.
> formulae: create failed dir only if nonexistent

- lib/test_cleanup.rb
We migrated all formulae away from needing linuxbrew/xorg last year, so this step should no longer be necessary.
> Don't automatically tap linuxbrew/xorg

- lib/test_bot.rb
This produces massive initialisation speedups when repeatedly running `brew` commands like `brew test-bot` does.
> lib/test_bot: use Bootsnap.

- lib/tests/formulae.rb
`installed_gcc` would always be reset to `false`.
> lib/tests/formulae: fix gcc install infinite loop

- lib/tests/formulae.rb
> lib/tests/formulae: don't error with if no tap is detected

- lib/test_ci_upload.rb
- spec/stub/github_releases.rb
Probably worth deprecating this at some point, signposting taps to use `brew pr-upload`.
> lib/test_ci_upload: fix error after brew changes

- lib/test_bot.rb
Caught by the CLI arg changes I'm making in https://github.com/Homebrew/brew/pull/10880.
> lib/test_bot: remove old --clean-cache dead code

- lib/tests/formulae.rb
Caught by https://github.com/Homebrew/brew/pull/10880.
> lib/tests/formulae: remove old --or-later reference

- lib/tests/formulae.rb
`native_regex` will likely go away in https://github.com/Homebrew/brew/pull/10948.
> formulae: fix bottle regex.

- lib/tests/cleanup_before.rb
This is failing `brew doctor`.
> cleanup_before: remove ansible config on Linux.

- lib/test_bot.rb
This PR changes BrewTestBot's email for consistency, as discussed in [this thread](https://github.com/Homebrew/homebrew-core/pull/74368#discussion_r605843396).
> lib/test_bot: change BrewTestBot's git email

- lib/tests/formulae.rb
95% means only 5GB free. Legacy LLVM versions (`llvm@9`, `llvm@8`) during a Python update needs a bit more than that, particularly since they're based on the old static-linking way of building which I didn't backport (and I probably won't for compatibility reasons).
90% is about 10GB free which most builds should be able to operate in.
The runtime cost of running this a tad more often seems negligible. It can be optimised in a similar manner to `Mktemp`'s cleanup if need be.
> lib/tests/formulae: change cleanup_during margin to 10GB

- cmd/test-bot.rb
- lib/tests/formulae.rb
Provide option to pass `--only-json-tab` to bottles (so they can be built reproducibly).
After this is merged: I'll open a PR to enable this on Homebrew/homebrew-core.
> Optionally build bottles with `--only-json-tab`

- lib/tests/formulae.rb
I'm pretty sure the bug is linked with sparse file handling, and we don't use sparse files under gnu-tar.
> lib/tests/formulae: only sudo purge without --only-json-tab

- .github/workflows/tests.yml
- .gitignore
- lib/test_runner.rb
- lib/tests/formulae.rb
I think this will be useful to not only quickly see the checksums of the bottles, but also see what is preventing the bottle from being relocatable.
Requires https://github.com/Homebrew/brew/pull/11307
> Write `brew bottle` output to text file.

- lib/tests/formulae.rb
This allows us to catch breakage from new versions of emscripten. See,
for example, https://github.com/Homebrew/discussions/discussions/1488.
Currently, this applies to only one formula (`tree-sitter`).
> lib/tests/formulae: build emscripten deps from source

- cmd/test-bot.rb
- lib/test_bot.rb
- lib/tests/formulae.rb
These were both disabled and now Bintray has been shut down for over a month and a half.
> Delete --bintray-org --ci-upload arguments.

- lib/tests/tap_syntax.rb
This PR modifies `test-bot` to exclude `ResourceAuditor#audit_version` where `brew audit` is run for existing formulae, so we avoid this audit on core CI. The version audit should still be run for new formulae, as we want to ensure that we catch an unnecessary `version`.
A detailed explanation of the reasoning behind this change can be found in Homebrew/brew#11542. It's fine to merge this test-bot PR independently and the version audit will be skipped after the brew PR is merged (as `ResourceAuditor` will start receiving the `--only` and `--except` options).
I'm not very familiar with `test-bot`'s internals, so any feedback on whether I've modified the correct `brew audit` calls would be appreciated.
> Exclude version audit

- lib/tests/formulae.rb
In relation to some [recent discussion about the `HOMEBREW_REQUIRE_BOTTLED_ARM` environment variable name](https://github.com/Homebrew/homebrew-core/pull/79458#discussion_r653131335), this PR modifies the related test-bot code to allow for an alternative `HOMEBREW_SKIP_UNBOTTLED_ARM_TESTS` environment variable.
This is intended to replace the existing environment variable but we'll need to temporarily allow both during the transition period. I added a preceding `TODO` comment that makes this clear.
I know this environment variable is set in homebrew/core's [`tests` workflow](https://github.com/Homebrew/homebrew-core/blob/1956fde72bb034d0f5688a8d2005fdb6f505516a/.github/workflows/tests.yml#L115) but are there any other areas that we would need to update as well?
> Rename ENV var to skip unbottled ARM tests

- lib/tests/formulae.rb
This is a follow-up to #619, which added support for a `HOMEBREW_SKIP_UNBOTTLED_ARM_TESTS` environment variable, as a way of renaming `HOMEBREW_REQUIRE_BOTTLED_ARM`.
After that PR was merged, we replaced usage of this environment variable in homebrew/core (in the `tests.yml` workflow), which appears to be the only place this is used. With that done, this PR removes support for the old `HOMEBREW_REQUIRE_BOTTLED_ARM` environment variable, as it's no longer used.
> Remove old ENV var to skip unbottled ARM tests

- cmd/test-bot.rb
> cmd/test-bot: remove GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED workaround.

- .gitignore
- cmd/test-bot.rb
- lib/junit.rb
- lib/step.rb
- lib/test.rb
- lib/test_runner.rb
This PR adds (or rather brings back) an ability to save `homebrew-test-bot` test results in JUnit format.
Most of the code is copied from the previous version (from https://github.com/Homebrew/homebrew-test-bot/pull/355) with some small adjustments:
- All JUnit related code moved to `lib/junit.rb`
- JUnit reporter supports filtering tests by name (currently is saves results only for `audit` and `test`)
See https://github.com/Homebrew/brew/pull/11578#pullrequestreview-689543802
> Add JUnit output format

- lib/tests/formulae.rb
The lists of dependents are reset to avoid long-running builds in linuxbrew-core.
Run that part of the code only in linuxbrew-core
> tests: modify dependents lists only in linuxbrew-core

- lib/tests/formulae.rb
This can be reverted if we think it is useless,
but I have been asking myself many times why
some dependents are being tested.
This should also help debug an issue we have right now with
homebrew-core.
> tests: add some debug output

- lib/tests/formulae.rb
Remove the check on the tap because I have the feeling that it is not always set.
We can skip :all bottles for the time being on any Linux env, as we don't
use :all bottles there.
Change the boolean detection logic, should work better now.
> tests: improve :all bottle detection logic

- lib/tests/formulae.rb
Whatever the value of HOMEBREW_SKIP_UNBOTTLED_LINUX_TESTS,
we want to skip :all bottles for dependents on Linux for
the time being
> tests: always skip :all dependents on Linux

- lib/tests/formulae.rb
Now that everything works as expected, I am adding this
check back (I removed it to make sure it did not break anything in a previous PR)
> tests: skip all bottles for Linux only in homebrew-core

- lib/test_bot.rb
I am trying to find out why tap is not set on linux CI for homebrew-core
> tests: add tap debug

- lib/tests/formulae.rb
The current logic does not work, is hard to understand and to debug. It is better to use early returns and specific error messages.
> test: split skip conditions for Linux with specific messages

- lib/tests/formulae.rb
and disable hard-coded dependency list for the time being
in homebrew-core for Linux
> tests: disable reverse dependency only in homebrew-core

- cmd/test-bot.rb
- lib/test_bot.rb
- lib/test_runner.rb
- lib/tests/formulae.rb
- lib/tests/formulae_detect.rb
This splits the current `--only-formulae` step into `--only-formulae` and `--only-formulae-detect`. This will allow the failures to be more obvious on whether they are due the detection of the changed formulae.
In a future PR I hope to split out `--only-formulae-bottle` and `--only-formulae-dependents`.  This will allow the failures to be more obvious on whether they are due to the changed formulae failing, the dependents of these formulae (or the detection of the changed formulae).
This future PR work should provide a few benefits:
- in future potentially cache the changed formulae bottles to avoid rebuilding them every time if they were built successfully last time (speeding up large PR rebuilds)
- in future potentially parallelising the dependent testing across multiple jobs/runners
- …
> Split formulae step into multiple steps

- cmd/test-bot.rb
- lib/test_formulae.rb
- lib/test_runner.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
- lib/tests/formulae_detect.rb
Extracted from https://github.com/Homebrew/homebrew-test-bot/pull/582
This further splits the current `--only-formulae` step into `--only-formulae`, `--only-formulae-detect` and `--only-formulae-dependents`.
This will allow the failures to be more obvious on whether they are due to the changed formulae failing, the dependents of these formulae (or the detection of the changed formulae). It also generally further splits up a large, hugely complex class.
This will enable future PR work which should provide a few benefits:
- splitting out the detection, changed formulae and dependent formulae into separate steps
- not attempting to build any dependents if any changed formulae fail
- in future potentially cache the changed formulae bottles to avoid rebuilding them every time if they were …
> Split out formulae dependents.

- cmd/test-bot.rb
- lib/test_bot.rb
- lib/test_formulae.rb
- lib/test_runner.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
- lib/tests/formulae_detect.rb
Add more switches and flags to customise `brew test-bot` behaviour.
These will be used to move more logic from `brew test-bot` into labels in the Homebrew/homebrew-core workflow and separate formulae detection, build and dependants testing.
While we're here, also cleanup some ugly output that I noticed.
> Add more arguments

- cmd/test-bot.rb
> Options --testing-formulae and --added-formulae and --deleted-formulae are mutually exclusive.
This was incorrect.
> cmd/test-bot: fix conflicts.

- lib/junit.rb
- lib/test_runner.rb
When these are passed but with empty values we want to skip `formulae_detect`.
While we're here, also fix an exception with `lib/junit`.
> lib/test_runner: fix args.*_formulae handling.

- lib/tests/formulae.rb
Use correct formula name variable when skipping.
> lib/tests/formulae: fix install_gcc_if_needed.

- lib/tests/formulae_dependents.rb
When partitioning dependents into build-from-source dependents versus other dependents, we earlier used to:
```
next false unless build_dependents_from_source_allowlist.include?(full_name)
```
This was modified to:
```
next false if args.build_dependents_from_source? && !build_dependents_from_source_disabled
```
However this is an incorrect conversion from `unless` to `if`, we must return early with `false` unless the dependent is to be built from source, which means `if !args.build_dependents_from_source`. Also we should use OR to check if building dependents from source is disabled (for Linux).
> formulae_dependents: fix dependent partitioning

- lib/tests/formulae_detect.rb
This should be no longer needed for us since we are using setup-homebrew action.
> formulae_detect: git fetch refs only in non Homebrew repos

- .github/workflows/tests.yml
- .gitignore
- lib/tests/formulae.rb
- cleanup `.github/workflows/tests.yml` to more closely resemble homebrew/core (the place we care the most about testing and not breaking)
- ignore `vendor` from Git (and therefore VS Code)
- try to fix #646 by creating a fuller path
> Various fixes

- Dockerfile
Based on dawidd6's recommendation
Fixes:
error: could not lock config file .git/config: Permission denied
Error: Command failed with exit 255: git
> Dockerfile: use copy instead of add

- lib/tests/formulae.rb
This is needed when using brewed curl to fetch and/or audit
formulae
See https://github.com/Homebrew/brew/issues/11705
> test-bot: install brewed curl if needed

- lib/tests/formulae.rb
As discussed on Slack, we already have a big chunk of formulae bottled for Linux in homebrew-core. Let's enable Linux CI for new formulae.
> formulae: don't skip testing new formulae on Linux

- lib/tests/formulae_dependents.rb
This PR ensures that we have all dependencies (runtime and test) linked while we test a formula.
Here's an original issue:
- Let's say we have 3 formulae in a test run `A`, `B` and `C`: `A` conflicts with `B`; `C` depends on `B`
- We unlink `B` while testing `A` (as a conflicting one)
- When we test `C`, `B` is still unlinked, and this could lead to a test failure for `C`
We got exactly this situation in 
- https://github.com/Homebrew/homebrew-core/pull/83573#issuecomment-902419098
- https://github.com/Homebrew/homebrew-core/pull/68089#issuecomment-757338842
- https://github.com/Homebrew/homebrew-core/pull/67615#issuecomment-751294621
Fixes https://github.com/Homebrew/homebrew-test-bot/issues/544
\cc @carlocab @scpeters
> formula_dependents: ensure dependencies are linked

- lib/test_bot.rb
Mojave Curl currently doesn't work (cf. Homebrew/brew#12161). Until we
have a fix in `brew`, let's set this in `test-bot` so that we can get CI
in Homebrew/core running again.
> lib/test_bot: set `HOMEBREW_FORCE_BREWED_CURL` on Mojave

- lib/test_bot.rb
Reverts Homebrew/homebrew-test-bot#668
We won't need this soon, and is going to be blocking our effort to ship any revision bumps to Curl dependencies.
> Revert "lib/test_bot: set `HOMEBREW_FORCE_BREWED_CURL` on Mojave"

- lib/tests/formulae.rb
This is needed to fix Homebrew/core CI. See Homebrew/brew#12167.
> lib/tests/formulae: install `ca-certificates` if needed

- lib/test_bot.rb
CI still isn't installing `ca-certificates` despite
b2b7bb0da889246e89c8ba06846e3c4e8bc19279. See
Homebrew/homebrew-core#86423.
----
I'll admit to not being sure why this is needed, as this should already be set given Homebrew/brew#12167.
> lib/test_bot: set `HOMEBREW_FORCE_BREWED_CA_CERTIFICATES` on Mojave

- lib/test_bot.rb
- lib/tests/formulae.rb
Let's use `DevelopmentTools.ca_file_handles_most_https_certificates?` to
avoid having to set `HOMEBREW_FORCE_BREWED_CA_CERTIFICATES` for
ourselves in `test-bot`.
> lib/tests/formulae: cleanup

- lib/tests/formulae.rb
`install_curl_if_needed` will not install `curl` if a formula declares
`using: :homebrew_curl` for a resource. Let's change that by checking
the resources for `using: :homebrew_curl` too.
Needed for Homebrew/homebrew-core#88330.
> lib/tests/formulae: install curl if resources use Homebrew curl

- lib/test_bot.rb
https://github.com/Homebrew/homebrew-test-bot/issues/688
The command `brew tap` no longer supports the flag `--full`, causes the error 
```
Calling `brew tap --full` is disabled! There is no replacement.
```
> lib/test_bot: dont pass --full flag to brew tap command

- lib/tests/formulae.rb
The current system requires too much manual intervention before a
formula is bottled. While bottling for Monterey, I discovered about two
dozen formulae that should have had ARM Big Sur bottles but didn't.
Presumably, I would have found more if I were trying to look.
Let's try to automate more of the bottling process by always attempting
a build on ARM and Linux. We avoid CI failures by using `skipped`
instead of `failed` whenever we encounter a build/test/linkage error on
a formula that hasn't been bottled for the current OS.
> lib/tests/formulae: remove ARM/Linux skip behaviour

- lib/tests/formulae.rb
There is a corner case where an unbottled dependency is added to a
bottled formula. The current behaviour would silently skip the build,
which is undesirable. Let's retain the old behaviour for this case,
which is to attempt the build anyway (and most likely fail).
I'm not certain this is the correct behaviour yet, but the old one is,
in my opinion, still better than what is happening now.
See Homebrew/homebrew-core#88797.
> lib/tests/formulae: tweak skipping formulae with unbottled deps

- lib/tests/formulae.rb
See Homebrew/homebrew-core#88956.
Also, while we're here, let's hide the `no_older_versions: false`
double-negative in the default argument.
> lib/tests/formulae: skip all bottles with unbottled deps

- lib/tests/formulae.rb
Test-only dependencies have no impact on the bottle that is built, so
there is no need to check that these dependencies are bottled on the
current OS before a formula is bottled.
Let's relax the requirement that a test dependency is bottled for the
current OS to a check that a test dependency has a usable bottle. At
worst, the older bottle doesn't work and the test will fail. If it does
work, there's no reason for this dependency to block bottling.
> lib/tests/formulae: relax test dep requirements when building bottles

- lib/step.rb
- lib/test.rb
- lib/test_formulae.rb
- lib/test_runner.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
This completes #687. It's not enough to call `skipped` because some
steps will still have a `:failed` status, and that will cause `test-bot`
to exit with an error.
> Ignore failures from unbottled formulae

- lib/test_formulae.rb
This got misplaced while refactoring in #691.
> lib/test_formula: fix method signature

- lib/tests/formulae_dependents.rb
There is no variable called `formula` in this method, so we should refer
to `dependent` instead.
> formulae_dependents: fix `bottled?` method call

- lib/tests/formulae.rb
New formulae have no bottles, but we don't want build/test/linkage
failures to only be warnings.
> lib/tests/formulae: error instead of warn for new formulae

- cmd/test-bot.rb
- lib/tests/formulae.rb
Passing this flag to `test-bot` will omit the `--online` flag from
`brew audit`, and also skip `brew livecheck`.
This is useful for at least three cases:
1. Bottling on a new OS/architecture. These failures should probably not
block this especially if the build/linkage/test and install audits
succeeded.
2. Failures which seem to occur only in CI. (cf.
Homebrew/homebrew-core#88329, Homebrew/homebrew-core#89042)
3. PRs which require revision bumps to multiple formulae. CI runs on
these PRs often take a very long time, and this makes fixing these
failures (which is sometimes not even possible) and then re-running
CI very impractical.
The last point is a particularly sore pain point for me, because I find
few things more frustrating than waiting a long time for CI to run only
to find that …
> Add a `--skip-online-checks` flag

- lib/test.rb
- lib/test_formulae.rb
- lib/tests/formulae.rb
Let's demote another class of CI failures from unbottled formulae to
warnings: attempting to build a formula with a dependency that is also
in the `@testing_formulae` array. We see this in Homebrew/homebrew-core#89193.
It would be nice to be able to restrict the failures we ignore to only
the unbottled ones, but we need to pass the `changed_dependencies` in
its entirety to `brew install` in order for `brew` to work out the
correct order to install these dependencies.
> lib/tests/formulae: demote more unbottled failures to warnings

- lib/test_formulae.rb
This is missing a `#to_s` call.
> lib/test_formulae: fix undefined method error

- lib/step.rb
- lib/test.rb
- lib/test_formulae.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
This implements a way to produce annotations for all errors in a
`test-bot` run. It requires baking in some assumptions that we are
testing formulae into a `Step`. In exchange, we get annotations on
relevant formula files.
Additionally, a `brew install` or `brew test` failure will place that
annotation on the `install` method or `test` block respectively.
To enable annotations on formula files, we add a `named_args` keyword
argument to the `test` method. Formula names (or `Formula` objects) should be
passed as the value of `named_args` for annotations to be emitted.
I've also moved the `ignore` logic into the `Step` class, so there
should be no need to call `Step#ignore` manually after a `test` if we
wish to ignore errors from that step. Instead, we pass
`ignore_failures: true` to `test`.
> Implement annotations for relevant errors

- lib/step.rb
- make the method definition stricter
- allow passing through a title
- don't use `<details`> (it's not rendered correctly) but instead make use of `title` and the output.
> lib/step: improve Actions annotations.

- lib/tests/formulae_dependents.rb
This might fix the `mathlibtools` error in https://github.com/Homebrew/homebrew-core/pull/89488
```
OSX 'readlink' command does not support option '-f', please install 'greadlink'. If you use 'brew', you can install 'greadlink' using 'brew install coreutils'
```
`mathlibtools` depends on `lean`, which depends on `coreutils`
```rb
Formula["mathlibtools"].deps.map(&:name) # => ["lean", "python@3.10", "six"]
Formula["mathlibtools"].recursive_dependencies.map(&:name) # => ["cmake", "gmp", "coreutils", "jemalloc", "lean", "pkg-config", "gdbm", "mpdecimal", "ca-certificates", "openssl@1.1", "readline", "sqlite", "xz", "python@3.10", "tcl-tk", "python@3.8", "python@3.9", "six"]
```
> formula_dependents: ensure recursive dependencies are linked

- lib/tests/formulae_dependents.rb
We started trying to link recursive dependencies in #711. However, this
causes `test-bot` to attempt to link runtime dependencies of build
dependencies (see reviews at #659). This will error out because those
dependencies will not be installed (cf. Homebrew/homebrew-core#89573).
Let's fix this by only attempting to link recursive dependencies that
are actually installed.
> lib/tests/formulae_dependents: link only installed formulae

- lib/tests/formulae_dependents.rb
This change checks for formulae that should be bottled but aren't. When
it finds one, it displays an annotation on the relevant formula.
Closes #678.
> formulae_dependents: display annotations for missing bottles

- lib/step.rb
Using `GitHub::Actions::Annotation` causes errors in the Linux
container. See #712.
> lib/step: skip annotations on Linux (for now)

- lib/tests/formulae_dependents.rb
This improves on #711 and #713 by using `Dependency.prune` to skip build dependencies and their recursive dependencies.
Using `Dependency.skip` instead of `next` is technically not needed because the return value of `recursive_dependencies` is not used. However, it makes the intent here clearer: skip the dependency, but continue iterating over its recursive dependencies so they can be linked too.
> formulae_dependents: prune build deps when linking test deps

- lib/tests/formulae_dependents.rb
This still doesn't fix the overzealous linking of formulae,
unfortunately. See Homebrew/homebrew-core#89621.
This reverts commit 85aaf199e2b236becd6c1286886fe3a59581f329.
> Revert "formulae_dependents: prune build deps when linking test deps"

- lib/test_formulae.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
Also, simplify handling of `:all` bottles.
Closes #705.
> Display unbottled dependencies when skipping

- lib/step.rb
1. Fix output grouping.
2. Don't join with `\n`. `@output.lines` doesn't strip each line, so
joining with a newline doubles the spacing.
While we're here:
1. Remove `type` from `#puts_github_actions_annotation`, since this
method can observe the `@status` directly.
2. Remove the redundant `#in_github_actions?` checks in
`puts_full_output`, since this is already checked for in
`#puts_in_github_actions_group`.
3. Reduce duplication in `os_string` and avoid hardcoding literals.
> lib/step: improve GitHub Actions logging and annotations

- lib/tests/formulae_dependents.rb
> formulae_dependents: traverse dep tree when linking dependencies

- lib/step.rb
This is currently an empty string on Intel macOS.
> lib/step: fix `os_string`

- lib/step.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
This should make whitespace placement in the CI log a bit more logical.
> Improve whitespace placement

- lib/tests/formulae_dependents.rb
If the `--build-dependents-from-source` flag is passed, then all
dependents are built from source. This is the current behaviour.
We change behaviour in two ways:
1. Build unbottled dependents from source if all its dependencies are
either bottled, or were built earlier in the `test-bot` run.
2. Build Linux-only formulae from source too (either with the
appropriate flag or when the above condition is true) instead of
always skipping source builds on Linux.
Building unbottled dependents will be useful for detecting dependents
which should be bottled after #714.
This change should also allow us to clean up a bit of code in the
`#dependent_formulae!` method. I've omitted that for now since I have a
pending PR (#717) which introduces conflicting changes.
> formulae_dependents: build more dependents from source

- lib/tests/formulae_dependents.rb
The `file` needs to be relative to the repository. I thought
`GitHub::Actions::Annotation` was supposed to take care of making the
path relative, but it seems to not be working.
Let's improve the output a bit while we're here.
> formulae_dependents: fix bottle notification

- lib/tests/formulae.rb
This is a better fix for the issue I tried to fix in #733.
Checking dependents against `@new_formula` allows you to declare a
formula dependency on a new formula added in the same PR. The same thing
is achieved by checking `@testing_formulae` instead, but also accounts
for the case where a PR fixes a previously-unbottled formula `x`, and
also makes `x` a dependency of another formula.
> formulae: check deps against `testing_formulae` instead

- lib/tests/formulae_dependents.rb
I trialled this behaviour in Homebrew/homebrew-core#89857, and it adds a
significant amount of time to the CI run. I'm still interested in
automating the detection of formulae that should be bottled, but I think
it requires a more nuanced approach.
In the meantime, let's restore the old behaviour that dependents are
built from source only when requested via a flag.
Closes #731.
> formulae_dependents: build dependents from source only on request

- lib/test_formulae.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
While doing some testing I discovered that adding two new formulae,
where one depends on the other, will cause the dependent to get
skipped.
Let's fix that by also using `#bottled_or_built?` to check dependencies.
> formulae: don't skip formulae with a dependent in the same test-bot run

- lib/tests/formulae_dependents.rb
Building dependents from source is an opportunistic linkage party. We
don't really need to see those warnings.
> formulae_dependents: skip strict linkage check when building from source

- .github/workflows/tests.yml
- lib/tests/formulae_dependents.rb
This fixes an issue where important etc/var files, which may have been nuked during the build stage, are missing.
Detailed at: https://github.com/Homebrew/homebrew-core/pull/85812#issuecomment-996325061
> formulae_dependents: run postinstall before testing dependents

- lib/tests/formulae_dependents.rb
The dependencies would have been uninstalled after the build stage to prevent opportunistic linkage, so they'll need to be reinstalled again when testing dependents.
This happened implicitly before, but it now needs to be explicit so that it's done before `postinstall`.
> formulae_dependents: install formula dependencies first

- lib/test_formulae.rb
The existing check is, unfortunately, still wrong. This is due to a
misunderstanding I had about the scope in which instance variables are
evaluated for derived classes.
This should be better now.
Spotted in Homebrew/homebrew-core#92329.
> test_formulae: fix check for just-built formulae

- lib/tests/formulae.rb
This is needed for #766.
Fixes 
```
Error: undefined local variable or method `testing_formulae' for #<Homebrew::Tests::Formulae:0x00007fc7530ee670>
```
https://github.com/Homebrew/homebrew-core/runs/4791063162?check_suite_focus=true#step:6:21
> lib/tests/formulae: add `attr_accessor :testing_formulae`

- lib/tests/formulae_dependents.rb
This is the same change as #767.
> formulae_dependents: allow reading from `testing_formulae`

- lib/test_runner.rb
- lib/tests/formulae.rb
The information from `brew linkage` is quite useful, and I often find
myself downloading bottles to check them.
This will allow us to see it in the CI log in the same way as the bottle
step output.
> tests/formulae: dump linkage output to file

- lib/tests/formulae.rb
Otherwise the output starts with
```
==> brew linkage --cached midgard2System libraries:
```
https://github.com/Homebrew/homebrew-core/runs/4856865138?check_suite_focus=true#step:10:14
> lib/tests/formulae: add a newline in linkage output

- lib/test_formulae.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
This is still happening despite my previous attempts to fix it. The
issue is that a formula is removed from the `@testing_formulae` array
once its bottle is successfully built, so I can't check this array to
determine whether a formula was successfully built earlier in the run.
Let's fix that by keeping track of formulae with built bottles
separately.
I tested this a lot more carefully than my previous attempts, so
hopefully this should do it now.
Needed for Homebrew/homebrew-core#92329, Homebrew/homebrew-core#93167,
and Homebrew/homebrew-core#92024.
> Fix bottling dependents of new formulae

- lib/tests/formulae_dependents.rb
> formulae_dependents: skip linking optional deps

- lib/test_cleanup.rb
Fixes a random `*.bottle_manifest.*` lock file deep in the Cellar being matched.
(I should also fix `.bottle` subdirectory dragging in lock files like that - but that's a separate issue.)
> test_cleanup: don't match --exclude recursively

- lib/test_formulae.rb
added keyword argument `build_bottle` to `FormulaInstaller.new` in order to delete `attr_writer` to be deleted which is stated in the comment https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_installer.rb#L45
> add keyword_argument to `FormulaInstaller#new`

- lib/tests/formulae_dependents.rb
Make use of the `brew uses --all` flag added in https://github.com/Homebrew/brew/pull/12935
Blocked on https://github.com/Homebrew/brew/pull/12935
> formulae_dependents: use `--all`.

- lib/tests/formulae.rb
This is a follow-up to #802, where I reworked some of the livecheck tests. It was [brought to my attention](https://github.com/Homebrew/homebrew-test-bot/commit/6e5b9dbd11338e55995293df9852ece37123af3d#r73450218) that I accidentally referred to the `livecheck_info` variable as `livecheck_json` in a couple places and this is predictably causing issues. This PR resolves the issue by renaming the misnamed variables.
> Fix misnamed variable

- lib/tests/formulae.rb
This method will be removed in https://github.com/Homebrew/brew/pull/13347.
> formula: remove use of bottle_disabled.

- lib/tests/formulae_dependents.rb
> tests/formulae_dependents: drop Debian 7 check

- lib/test_bot.rb
This will help stop taps that make use of `test-bot` from producing
bottles with linkage to `libcrypt.so.1`. Linking with `libcrypt1.so.1`
is deprecated and will be broken when we ship a new `glibc` that does
not include `libcrypt.so.1`.
> Set `HOMEBREW_DISALLOW_LIBCRYPT1`

- lib/tests/tap_syntax.rb
This is no longer needed. See Homebrew/brew#13750.
This reverts commit 82ce00faf85401a8b9067543f96d1d15dbe01952.
> Revert "tap_syntax: exclude GCC dependency audit."

- lib/tests/tap_syntax.rb
This doesn't slow the tap syntax job down by much:
| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `brew audit --tap=homebrew/core --except=version` | 143.878 ± 2.262 | 140.325 | 146.362 | 1.00 |
| `brew audit --tap=homebrew/core ` | 145.160 ± 2.476 | 141.643 | 148.119 | 1.01 ± 0.02 |
Benchmark conducted on Ubuntu 20.04 with `HOMEBREW_SIMULATE_MACOS_ON_LINUX` set, against
```
Homebrew 3.5.10-49-gb2ddb34
Homebrew/homebrew-core (git revision c78aa5d8dd8; last commit 2022-08-25)
```
More details available [here](https://github.com/carlocab/workflow-test/actions/runs/2928925233/attempts/1#summary-8023071550).
> tap_syntax: remove `--except=version`.

- lib/tests/formulae.rb
This is useful for debugging and will detect circular dependencies.
Fixes https://github.com/Homebrew/brew/issues/13774
> formulae: run `brew deps --tree`

- lib/tests/formulae_dependents.rb
The dependencies of build dependencies do not inherit the `:build` tag
when expanding via `#recursive_dependencies`. This results in `test-bot`
testing build-only dependents when it doesn't need to. See
Homebrew/homebrew-core#109250.
Let's fix that by pruning the dep tree whenever we encounter a build
dependency while expanding a dependent's dep tree. In the case of
`ninja`, this will result in `test-bot` correctly identifying that it
only needs to test formulae with a runtime dependency on `ninja`.
> formulae_dependents: prune more recursive dependencies

- lib/tests/formulae.rb
Fixes multiple
Error: GitHub API Error: Bad credentials
HOMEBREW_GITHUB_API_TOKEN may be invalid or expired; check:
https://github.com/settings/tokens
errors seen at Homebrew/homebrew-core#98809.
Formulae are removed from `@testing_formulae` after they are tested, so
we cannot use this to count the number of formulae being tested.
> tests/formulae: fix check for skipping online checks

- lib/test_bot.rb
The bottles that we ship that link to the old `libnsl` will break on
systems with newer Glibc. Any existing bottles that have this linkage
have likely already been broken by upgrading `glibc` to 2.35.
Also, `HOMEBREW_DISALLOW_LIBCRYPT1` is now a no-op, so we can get rid of
it.
> lib/test_bot: disallow `libnsl.so.1`.

- lib/tests/formulae.rb
This will help us get rid of these as formulae are updated.
> formulae: audit for Linux-only GCC dependencies.

- Dockerfile
We should use `ubuntu22.04` as in everywhere else.
> Dockerfile: update image.

- lib/tests/formulae.rb
Let's fail more quickly if a formula has a Linux-only GCC dependency to
avoid wasting CI time on a build that we don't intend to use.
> tests/formulae: audit Linux-only GCC dependency earlier.

- lib/tests/formulae.rb
This is needed to make sure we don't try to test any of the formula's
dependents.
> tests/formulae: call `skipped` when GCC audit fails.

- lib/tests/formulae_dependents.rb
This second call to `brew uses` is for identifying build dependents, so
we need to pass `--include-build`.
Needed for Homebrew/homebrew-core#110461.
> formulae_dependents: pass `--include-build` to second `brew uses` call.

- cmd/test-bot.rb
- lib/tests/formulae.rb
Sometimes livecheck will work for a formula locally but fail on CI (intermittently or consistently) and this can force us to merge a PR with failing CI when there isn't an obvious solution. Ideally, we should identify the underlying source of the failure and resolve it but a `--skip-livecheck` option may be useful when that's not immediately possible or the failure point is out of our control (e.g., an upstream server issue).
For example, the `livecheck` blocks for the `aqbanking` and `gwenhywfar` formulae work fine locally but have consistently timed out on macOS CI since around January 2022 and PRs have simply been merged despite the CI failure. This is currently the case in Homebrew/homebrew-core#110571, so I thought we may want to consider making it possible to optionally skip …
> Add `--skip-livecheck` option

- lib/tests/tap_syntax.rb
An audit of no files now throws an error.
Needed for e.g. https://github.com/Homebrew/homebrew-formula-analytics
> tap_syntax: only readall/audit if formula/cask files exist.

- lib/tests/formulae.rb
Not tested, but this should hopefully prevent reoccurrences of https://github.com/Homebrew/homebrew-core/pull/115951.
> tests/formulae: make dependency tree failures an annotation

- lib/test_bot.rb
This is causing mass `brew audit` failures currently.
> lib/test_bot: don't install from API (yet, at least).

- .github/workflows/tests.yml
- lib/tests/formulae.rb
- lib/tests/formulae_detect.rb
This PR replaces the `set-output` commands with the `GITHUB_OUTPUT` environment file to set the outputs in GitHub Actions.
Ref: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> test-bot: replace set-output with GITHUB_OUTPUT

- lib/test_bot.rb
- lib/test_cleanup.rb
- lib/tests/cleanup_before.rb
Needed for Homebrew/actions#332.
Allowing at least the bare minimum of this to work without Homebrew/core tapped seems sensible.
This fix is for non-core CI primarily as we should be tapped still for core CI.
> Fix errors when Homebrew/core is untapped

- lib/test_cleanup.rb
To cover the cases where you use `--only-cleanup*` outside of a tap (like we do in Homebrew/brew).
> test_cleanup: handle case untapped Homebrew/core edge case

- lib/tests/formulae_detect.rb
Noticed this in https://github.com/Homebrew/homebrew-core/pull/124234 and https://github.com/Homebrew/homebrew-core/pull/124427. They should have failed the notability audit, but since @BrewTestBot did not classify them as added, no `brew audit --new` was done.
This should also explain why CI failed in https://github.com/Homebrew/homebrew-core/pull/124431 where the formula is removed.
This logic was added in https://github.com/Homebrew/homebrew-test-bot/pull/876.
> formulae_detect: fix classification of formulae

- lib/test_runner.rb
This was replaced by a method in `Utils`, but we don't really need that
here either.
See Homebrew/brew#14778.
> Remove use of `pluralize`

- lib/test_runner.rb
- lib/tests/formulae.rb
The list of skipped or failed formulae is currently not being passed
correctly to the separate `test_deps` job after this was split in
Homebrew/homebrew-core#125595.
The current way of passing this list through step outputs is tricky to
get right with matrix jobs. However, we already pass a `bottles`
artifact between these jobs, so we can use that to record the
information that we need to pass on to the `test_deps` job.
When this is merged, we only need to remove the
`--skipped-or-failed-formulae` argument in the `brew test-bot`
invocation in the `test_deps` job.
> Fix passing of `skipped_or_failed_formulae` to `test_deps`

- lib/tests/formulae_dependents.rb
Sometimes, we might install multiple bottles that conflict with each
other. This results in an error when we install the second conflicting
bottle.
See https://github.com/Homebrew/homebrew-core/actions/runs/4572386951/jobs/8072393102?pr=127134#step:7:30
> formulae_dependents: unlink formula after bottle install

- lib/tests/formulae_dependents.rb
`brew postinstall` keeps failing in Homebrew/homebrew-core#127133. Let's
add some output to try to debug this.
> formulae_dependents: add debug output

- lib/tests/formulae_dependents.rb
This is also for Homebrew/homebrew-core#127133.
> formulae_dependents: add more debug output

- lib/tests/formulae_dependents.rb
This should fix the problem we're seeing at
Homebrew/homebrew-core#127133.
> formulae_dependents: link before installing dependencies

- lib/tests/formulae_dependents.rb
This fix from #895 seems to have worked, so we shouldn't need these
anymore.
> formulae_dependents: remove debug output

- lib/tests/formulae.rb
Previously, this assumed that the bottle filename was resolved by falling back to the path in the URL, e.g. `0.1.tgz` if there was a server error.
Fixes the CI error in https://github.com/Homebrew/brew/pull/15117, which makes resolving the file name a hard error in case the server returns e.g. 404.
> Properly stub resolved bottle filename.

- lib/tests/formulae_detect.rb
Casks are only ever under `Casks` but formulae can be in many places (including the repository root).
Fixes #897
> formulae_detect: reject casks.

- lib/tests/formulae_detect.rb
This PR reverts PR #899 which fixed issue #897.
The cause of #897 was later identified as coming from `Homebrew/brew` itself, and has been fixed in
- https://github.com/Homebrew/brew/pull/15150
Thus in `homebrew-test-bot` here #899 can be safely reverted.
> Revert "Merge pull request #899 from Homebrew/formula_detect_cask"

- lib/test_formulae.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
On some long-running CI runs, you can see multiple consecutive calls to
`#cleanup_during!` in the CI log. This indicates that the runner is
close to running out of space, but deleting `HOMEBREW_CACHE` isn't quite
going far enough in clearing it out.
Let's try to improve that by uninstalling installed formulae that are
safe to uninstall on the second call to `#cleanup_during!` onwards.
> Improve `#cleanup_during!`

- cmd/test-bot.rb
- lib/test_runner.rb
- lib/tests/bottles_fetch.rb
- lib/tests/formulae_fetch.rb
This will allow us to check that the built bottles can be fetched before
merging a PR.
Note: `--retry` does not actually work for `brew fetch` when fetching
bottles. This will need to be fixed in `brew`.
> Add `--only-bottles-fetch` flag

- lib/tests/formulae_detect.rb
This should allow `--only-formulae-detect` to work inside a merge group.
We probably also want to merge #905 so we can test this properly.
> formulae-detect: fix merge group detection

- lib/tests/formulae_detect.rb
Here, `origin_ref` points to the temporary merge group branch, so it
will be the same as `GITHUB_SHA`.
> formulae_detect: actually use `origin/master` for starting SHA1

- lib/tests/formulae_detect.rb
Instead, let's use the same workaround for `push` jobs while it isn't
fixed.
> formulae_detect: remove merge group workaround

- lib/test_cleanup.rb
- lib/tests/cleanup_before.rb
These directories contain headers and libraries that we don't want to
use, so let's get rid of them when building on a GitHub macOS runner.
The Mono framework in particular contains Gettext headers that I've seen
mess up CMake builds in the past.
> cleanup_before: clean `/Library/Frameworks` directory

- cmd/test-bot.rb
Passing `--local` depending on whether the runner is self-hosted or not
complicates our handling of log directories in Homebrew/core.
Always setting it ensures that we can always look in the same place
relative to the bottles directory for the logs, and will allow us to
simplify some code in our workflows.
This also fix log uploads when using GitHub macOS runners for testing.
> cmd/test-bot: always set `--local` in GitHub Actions

- lib/tests/formulae.rb
This will help us save CI time, and fixes an error in dependent testing
when we try to install a bottle that we never built.
> tests/formulae: skip formulae with no bottles to build

- lib/tests/formulae.rb
If the bottle step fails, these should be added to
`skipped_or_failed_formulae` so we don't attempt to test them later.
> formulae: skip formulae with failing bottle steps

- lib/tests/tap_syntax.rb
This should avoid making changes in taps that break API generation.
This is maybe not the right place for this to live but it felt most appropriate to me.
See also https://github.com/Homebrew/brew/pull/15404
> tests/tap_syntax: test API generation.

- .github/workflows/tests.yml
- lib/test_formulae.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
- spec/stub/utils/github/artifacts.rb
This allows us to limit having to rebuild bottles that have already been
successfully built earlier.
~TODO: Actually install the downloaded bottles. Also needs
Homebrew/brew#15440 and Homebrew/brew#15441.~
> tests/formulae: download bottles from previous CI runs

- .github/workflows/tests.yml
- Dockerfile
This should help simplify this workflow a bit.
> workflows/tests: use `container`

- lib/tests/formulae.rb
Returning early from `bottle_reinstall_formula` is expected for a dry
run.
> tests/formulae: do not call `failed` in a dry run

- lib/tests/formulae.rb
The most likely cause for this is use in a repo that isn't
Homebrew/core. See, for example, Homebrew/brew#15485.
Closes Homebrew/brew#15486.
> formulae: ignore API authentication failures when downloading bottles

- lib/tests/formulae.rb
These are run without Homebrew/core checkouts. Let's avoid failing
those.
> tests/formulae: fix failing `Homebrew/brew` tests

- lib/tests/formulae.rb
`before` will be a SHA1 for Homebrew/brew, but `repository` points to
`Homebrew/core`, so trying to fetch that SHA1 will always fail in
Homebrew/brew.
> tests/formulae: fix Homebrew/brew tests (again)

- lib/tests/formulae.rb
The earlier fix also wasn't quite correct, since `tap` can be `nil`.
This is much simpler and handles Homebrew/brew tests better.
> tests/formulae: simplify fix

- lib/tests/formulae.rb
Without this we risk skipping builds of dependents of just-built
formulae in a PR.
> tests/formulae: add cached formulae to `@built_formulae`

- lib/tests/formulae_dependents.rb
`unlink_conflicts` skips keg-only formulae, so trying to `brew link`
these formulae can result in `brew link` failures.
> tests/formulae_dependents: do not `brew link` keg only formulae

- .github/workflows/tests.yml
- lib/step.rb
- lib/test_formulae.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
Our current method of using artifacts as a cache breaks when a PR is
pushed to multiple times in quick succession.
This is because we use the SHA1 prior to the most recent push to look up
artifacts, but there will be no useable artifacts to find there after
pushing to a PR that has recently been pushed to.
We can improve this by looking for an even earlier SHA1 to try to find
useable artifacts from.
This is a companion to Homebrew/homebrew-core#132093.
> test_formulae: improve result caching

- lib/tests/formulae.rb
This should help minimise the probability that these bottles were
tampered with.
> tests/formulae: verify local bottles before attempting to install one

- lib/test_formulae.rb
Let's report the Git revisions used to make it easier to audit the state
of the repo at the time the relevant bottle was built.
> test_formulae: improve logging of cached bottle installs

- lib/tests/formulae.rb
Trying to fetch a just-built dependency will result in a `brew fetch`
failure because its bottle will not have been uploaded yet.
See Homebrew/homebrew-core#133144.
> formulae: avoid fetching just-built dependencies

- lib/tests/bottles_fetch.rb
It looks like the runner is running out of space doing this at
Homebrew/homebrew-core#133740.
> bottles_fetch: run `cleanup_during!` more often

- lib/tests/formulae.rb
- lib/tests/formulae_detect.rb
- lib/tests/tap_syntax.rb
Everything in a CI environment worked ok. This is just small tweaks so that a `brew test-bot hello` on the command line switches to no-API mode.
> tests: improve no-API switching for named args

- lib/test_formulae.rb
We can correctly follow the trail left by the PR `event.json`s but still
end up in an infinite loop for some reason.
Let's avoid this by giving up as soon as we find we're trying to
download an artifact we've already seen before.
Fixes a CI failure at Homebrew/homebrew-core#134939.
> test_formulae: avoid repeated downloads of the same artifact

- lib/test_bot.rb
These are just a bit annoying in `brew test-bot` output.
> lib/test_bot: no environment hints.

- lib/tests/formulae.rb
When https://github.com/Homebrew/brew/pull/15941 is merged this will be run as part of the normal audit run.
> formulae: don't do separate `gcc_dependency` audit

- lib/tests/formulae.rb
- lib/tests/tap_syntax.rb
- only run `readall` or `audit` on the whole tap for `push` and `merge_group` runs.
- always run `brew style` on the formula in case `tap_syntax` isn't run or there's macOS/Linux differences as it's really fast.
> tests: speed up non-push/merge group cases.

- lib/test_formulae.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
This restores changes made in https://github.com/Homebrew/homebrew-test-bot/commit/fab38f1bfad42221f7af06a58ca72b62228f5eb6 that were lost in https://github.com/Homebrew/homebrew-test-bot/commit/cbe87b4b5a7ad44b70ea34d593c797b660db5f0d.
In summary, this PR:
* Changes the order of formulae we run dependent testing on to be the same order as the formulae were built. This means it's roughly topological now so the postinstalls will now be run in the correct order should one formula we're testing the dependents of is a dependency of another such formula.
* Dependents of multiple formulae will now be deferred as much as possible rather than eagerly tested when they're first encountered. This again ensures we're only testing things after all the relevant postinstalls have happened.
Should fix …
> Improve dependent test ordering

- lib/tests/tap_syntax.rb
This is a follow-up to changes that added os/arch combinations a few months ago. They were made the default temporarily until the references to `brew readall` in the other Homebrew repos were updated as well.
- https://github.com/Homebrew/brew/pull/15470
- https://github.com/Homebrew/brew/pull/15937#discussion_r1313889254
> Add os/arch options to readall command

- lib/tests/setup.rb
This would get picked up eventually by `brew style`, but let's be explicit here so that the time spent is obvious.
> tests/setup: explicitly select gem groups

- lib/tests/tap_syntax.rb
After perf and coverage improvments, we can simplify this for an overall speed boost.
I've also explicitly added a `--except=installed` here. It's not needed for most of our CI, but might be on `macos-latest`. The result of tap_syntax shouldn't be dependent on what formulae happen to be installed - these checks are best suited (and are run) on a per-formula basis in formula tests. We do not guarantee the speed of installed-formula audits, as it largely varies on how big formulae are and all our perf improvements haven't considered installed-formula audits.
> tests/tap_syntax: simplify and speed up

- .github/dependabot.yml
- .github/workflows/tests.yml
- Gemfile
- Gemfile.lock
- lib/junit.rb
We're moving away from 2.6 and the rspecs tests here don't _need_ to be running 2.6 still, particularly when we still have `brew test-bot` commands being run in the workflow which will be use Homebrew's Ruby. It might also give us an early warning of Ruby 3.1 issues, though the rspec test coverage here is extremely minimal.
Also update `actions/cache` to v3 since we support that now in setup-homebrew.
> Update rspec Ruby, Gemfile, actions/cache, etc.

- lib/test_runner.rb
REXML will not be available with Ruby 3 and JUnit output currently needs it. However, we only really need JUnit output when doing the formula steps (because we filter for `audit` and `test`), and formula steps assume that `brew test-bot --only-setup` has already been run with the `brew install-bundler-gems --groups=...` it internally does, so simply making sure it only is executed when running those steps should address the issue.
> test_runner: scope JUnit output to only formula steps

- lib/tests/formulae.rb
See https://github.com/Homebrew/brew/pull/16224
This PR makes it so that all references to the `MacOS` module are gates behind `OS.mac?` calls to allow the `MacOS` module to be deprecated on Linux.
My only outstanding question is whether this reference needs to be changed:
https://github.com/Homebrew/homebrew-test-bot/blob/9da1d1f7f4de703c517c22dbdc237725ed4cd5ac/spec/stub/os.rb#L3-L9
This is in the test directory so it shouldn't affect functionality, only CI in this repo.
> Gate `MacOS` calls behind `OS.mac?` conditionals

- lib/test_bot.rb
- lib/tests/formulae.rb
This is way too fragile and has broken multiple times before (it's why we have `/github/home` manually set as the working directory in a few places), including from changes like https://github.com/Homebrew/brew/pull/16245. It relies far too much on brew internals and we forgot to even update when switching to GitHub Packages until two years later. I'm not entirely sure how anyone even noticed in the end. It also has never supported manifest linking.
I'm not sure if it's even necessary anymore. The formulae intentionally stay installed so when would we be fetching it again? I'd like to try without this and see what breaks. If nothing: great. If there is something: I'd like to see if there's a better way to fix it as it might mean something is getting fetched unnecessarily.
The cleanup side …
> Remove bottle cache hard linking

- lib/tests/formulae.rb
`--new-formula` was deprecated in https://github.com/Homebrew/brew/pull/16306
Fixes https://github.com/Homebrew/homebrew-test-bot/issues/991
> tests/formulae: use `--new` flag.

- cmd/test-bot.rb
- lib/tests/formulae.rb
I recently split the stable version formula audit into a separate method that can be skipped using `--except` (https://github.com/Homebrew/brew/pull/16335). This adds a `--skip-stable-version-audit` option to test-bot that passes `--except=stable_version` to `brew audit`. This will be controlled in homebrew/core using a `CI-version-downgrade` label (for when we need a downgrade PR to run on CI).
Alternatively, if we want something more general purpose, we could add an `--audit-except` (or `except-audit`) option instead. That could potentially save us from having to add additional options like this that simply skip an audit. The only catch is that we would have to make sure to collect the `except` args in CI workflows and only pass `--audit-except` once to test-bot.
> Add option to skip `stable_version` audit

- lib/test_formulae.rb
As discussed internally in Slack, this allows us to disable bottle cache more intuitively.
> test_formulae: allow disabling bottle cache with `CI-no-bottle-cache` label

- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
- lib/tests/formulae_detect.rb
Previously we were ignoring a bunch of failures in these cases which makes this CI check pretty useless (e.g. see https://github.com/Homebrew/brew/pull/16423).
> Fix `ignore_failures` usage with `--test-default-formula`

- lib/tests/cleanup_before.rb
This ensures that there's no lingering bad symlinks (either already broken or broken by our previous cleanup steps) after the OS-wide cleanup happens.
This was necessary to add in https://github.com/Homebrew/brew/pull/16576 but there's enough other places this is needed and it didn't slow things down much so it's worth just doing by default.
> cleanup_before: cleanup prefix on GitHub Actions (not self hosted).

- lib/test_formulae.rb
It occurred to me that bottle cache is not enabled for PRs from @BrewTestBot. Let's enable that.
> test_formulae: allow bottle cache in @BrewTestBot PRs

- lib/tests/formulae_detect.rb
- spec/spec_helper.rb
- For https://github.com/Homebrew/brew/pull/16745.
> Fix RuboCop `Lint/RedundantDirGlobSort` and `Performance/MapCompact` offenses

- lib/tests/formulae.rb
seeing audit failure in https://github.com/Homebrew/homebrew-core/actions/runs/8320806246/job/22766174322?pr=165919
```
Full audit yo --online --new output
Error: No such file or directory @ rb_check_realpath_internal - /opt/homebrew/Library/Taps/homebrew/homebrew-cask/Casks/yo.rb
```
----
- similar to #1017
- relates to https://github.com/Homebrew/homebrew-core/pull/165919
> formulae: scope `brew audit`

- lib/tests/formulae.rb
This project is complete, so we can remove this.
Reverts Homebrew/homebrew-test-bot#950
> Revert "tests/formulae: skip online checks for OpenSSL migration PRs"

- cmd/test-bot.rb
- lib/tests/formulae.rb
We often need to skip repository checks (repo age, notability, etc.) for various reasons. This PR allows us to skip those checks with a switch, so that we can reduce the number of ❌ PR's we are merging in homebrew-core.
> test-bot: allow skipping repository audit

- lib/test_formulae.rb
On Linux by default, `HOMEBREW_LOGS` (`~/.cache/Homebrew/Logs`) is a subdirectory of `HOMEBREW_CACHE` (`~/.cache/Homebrew`). This means that `cleanup_during!` deletes the logs for the already-tested formulae, which is not ideal because these logs are to be uploaded as an artifact. These logs don't usually take up as much space as the cached downloads, and can be valuable for debugging, especially when a PR involves too many formulae that GitHub Actions cannot show all the logs.
Instead, we can move the logs to a temporary directory, and restore them after the cleanup.
> test_formulae: preserve logs in `cleanup_during!`

- lib/test_formulae.rb
Follow-up to #1034.
Fixes failures seen in https://github.com/Homebrew/homebrew-core/actions/runs/8591317346/job/23561568330?pr=168136.
> test_formulae: only save logs if `HOMEBREW_LOGS` exists

- cmd/test-bot.rb
- lib/tests/tap_syntax.rb
Related to https://github.com/Homebrew/homebrew-core/pull/166913
Wasn't sure if we wanted a mutually exclusive arg (and optionally a separate Test) or just a dependent arg. Went with the simplest change which is `--stable` option.
> Add stable option to restrict tap syntax checks

- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
We don't need to download cached artifacts for other OSes/MacOS
versions, so let's skip doing that where we can.
> tests: download only needed cached artifacts

- Gemfile
- Gemfile.lock
- lib/test.rb
- spec/spec_helper.rb
- spec/stub/utils/analytics.rb
This is used to identify the failure/success rate of various commands.
Requires https://github.com/Homebrew/brew/pull/16847
> test: report test bot test results to analytics.

- lib/test.rb
- lib/tests/formulae.rb
Only report for `install`, `style`, `audit`, `linkage`, and `test` steps for now. Everything else is a bit too noisy (and not flaky).
> Selectively report analytics.

- lib/tests/formulae.rb
Follow-up to #1041. Fixes:
Error: CLI arg for `skip_strict?` is not declared for this command
Seen in Homebrew/homebrew-core#170246.
> formulae: fix CLI arg name

- lib/tests/formulae_detect.rb
Should fix:
```console
Error: Calling `CoreTap.ensure_installed!` is deprecated! Use `CoreTap.instance.ensure_installed!` instead.
Please report this issue to the Homebrew/homebrew-test-bot tap, or even better, submit a PR to fix it:
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-test-bot/lib/tests/formulae_detect.rb:51
```
> Fix deprecated `CoreTap.ensure_installed!`

- .github/workflows/tests.yml
If a bottle starts with a `-`, this could be interpreted as an option. Use `--` to mark end of options.
> tests.yml: adjust `rm` command

- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
1. Avoid downloading artifacts built for Apple Silicon on Intel
2. Make sure to download artifacts built on GitHub-hosted runners too
> Update bottle cache specifiers

- lib/tests/bottles_fetch.rb
We don't really care if bottles for disabled formulae will fail to
fetch.
> bottles_fetch: skip disabled bottles

- cmd/test-bot.rb
- lib/test_bot.rb
- lib/tests/formulae.rb
While fixing `brew style` tap support (https://github.com/Homebrew/brew/pull/17482), brew CI surfaced some style issues in the test-bot tap. This fixes the style issues, so brew CI will pass and the fix can be merged.
> Fix style issues

- lib/tests/setup.rb
This is now bundled in Portable Ruby and we will remove it from other Rubies: https://github.com/Homebrew/brew/pull/17534
> tests/setup: remove bootsnap install

- lib/test_formulae.rb
Maintainers are now encouraged to branch directly on homebrew-core.
> test_formulae: only allow fork build cache usage for BrewTestBot forks.

- lib/tests/formulae_dependents.rb
We're experiencing long waits on CI for Intel macOS runners, so this
should alleviate that somewhat.
> formulae_dependents: always skip recursive dependents on Intel macOS

- lib/tests/formulae_dependents.rb
This allows us to skip some steps that aren't needed[^1] for formulae with
no dependents.
[^1]: e.g. `brew link`, `brew install --only-dependencies`, etc.
> formulae_dependents: skip unnecessary steps when there are no dependents

- lib/tests/tap_syntax.rb
- Part of https://github.com/Homebrew/brew/issues/17297.
- I didn't just run on all taps right now because otherwise it's going to block and we don't want to have to Sorbetify a tap to unblock a PR, that's a lot of work.
> Run `brew typecheck` as part of (some) `tap_syntax` tests

- cmd/test-bot.rb
- lib/junit.rb
- lib/step.rb
- lib/test.rb
- lib/test_bot.rb
- lib/test_bot.rbi
- lib/test_cleanup.rb
- lib/test_cleanup.rbi
- lib/test_formulae.rb
- lib/test_formulae.rbi
- lib/test_runner.rb
- lib/test_runner.rbi
- lib/tests/bottles_fetch.rb
- lib/tests/cleanup_after.rb
- lib/tests/cleanup_before.rb
- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
- lib/tests/formulae_detect.rb
- lib/tests/setup.rb
- lib/tests/tap_syntax.rb
- spec/stub/os.rb
- spec/stub/tap.rb
- Part of https://github.com/Homebrew/brew/issues/17297, making another tap `typed: true`.
> Basic Sorbet `typed: true`

- lib/tests/tap_syntax.rb
- For some reason this isn't triggering, see https://github.com/Homebrew/homebrew-command-not-found/actions/runs/10499444382/job/29086226541#step:4:14. Since the `grep` works fine for me locally, my hypothesis is something to do with the tap path on the CI runner.
> Debug typechecking not triggering in tap_syntax

- lib/test_runner.rb
- lib/tests/tap_syntax.rb
- So that `git -C /path/to/tap grep ...` works correctly to determine if a tap should be typechecked.
- Thanks for your patience with my various test PRs, here's it working: https://github.com/Homebrew/homebrew-command-not-found/actions/runs/10516250377/job/29138543034.
> Pass `git` into `tap_syntax` tests

- lib/tests/tap_syntax.rb
- Since `brew typecheck <tap>` is not in a `brew` release yet, we need to skip this for stable `tap_syntax` checks otherwise: https://github.com/Homebrew/homebrew-core/actions/runs/10516750573/job/29139564452?pr=182076
> Skip `brew typecheck` if running on stable

- lib/tests/formulae_detect.rb
Currently this method takes either a String or a Pathname which is fine since we were passing in a Pathname. I'm planning on changing that behavior in new PR so that it will only accept the String class going forward so I'm updating this to use the String class here. This should be completely backwards compatible.
- Relevant PR: https://github.com/Homebrew/brew/pull/18167
I'm not too familiar with this repo so I'm not entirely sure how to test this change.
> Update usage of `Tap#formula_file?`

- lib/test_formulae.rb
The `title` doesn't show up in the workflow log, so let's make the
message a bit more verbose instead.
The `title` does show up in the file annotation, so let's still have one
but make it shorter.
> Improve bottle cache annotations

- lib/tests/formulae_dependents.rb
Fixes CI failures at Homebrew/homebrew-core#183951.
See https://github.com/Homebrew/homebrew-core/actions/runs/10761407159/job/29844078861?pr=183951#step:4:51
> formulae_dependents: fix fetching empty array of formulae

- cmd/test-bot.rb
- lib/test_runner.rb
- lib/tests/formulae_dependents.rb
This is needed for Homebrew/homebrew-core#182696.
The problem that lead to the revert in Homebrew/homebrew-core#182754 is
due to `test-bot` not realising that there are dependents we had already
tested in the earlier formulae build job that do not need to be tested
anymore.
We can fix this by making sure `test-bot` knows all the formulae we had
previously tested passed via a `--tested-formulae` flag.
For clarity, let's rename the old `@tested_formulae` ivar to
`@testing_formulae_with_tested_dependents`.
> Add `--tested-formulae` flag

- lib/step.rb
We're encountering intermittent `LoadError`s for msgpack on macOS 15.
It's not clear how to reproduce these errors, so let's sleep for an hour
when we see this to give @Bo98 the chance to log in and investigate.
> lib/step: sleep after encountering msgpack `LoadError` on macOS 15

- lib/step.rb
This is no longer needed.
Reverts Homebrew/homebrew-test-bot#1208
> Revert "lib/step: sleep after encountering msgpack `LoadError` on macOS 15"

- lib/tests/formulae.rb
We keep seeing `LoadError`s for msgpack, and this seems to make it go
away.
> formulae: run `sudo purge` before `brew style`

- lib/tests/formulae_dependents.rb
Except if we're testing a Linux-only formula.
This should help ease the load on our self-hosted Linux runner.
> formulae_dependents: skip recursive dependents on Linux

- lib/test_bot.rb
This might help with the intermittent bottle build issues on Sequoia.
> Skip `HOMEBREW_BOOTSNAP` on Sequoia

- lib/test_formulae.rb
`bottle_commit_details` can contain extraneous newlines, which makes the
log output a bit weird to parse. Let's fix that by calling `#strip`.
> test_formulae: strip `bottle_message`

- lib/tests/formulae_dependents.rb
This will allow us to skip attempting to test formulae that were never
built (because they're not compatible with the current runner).
Needed for Homebrew/homebrew-core#187308.
> formulae_dependents: remove incompatible formulae from `@dependent_testing_formulae`

- lib/tests/formulae_dependents.rb
Fixes
```
Error: Failed to find bottle for 'opencv'.
```
https://github.com/Homebrew/homebrew-core/actions/runs/10853013996/job/30140584720?pr=187308#step:3:62
> formulae_dependents: don't clobber existing `skipped_or_failed_formulae`

- lib/tests/formulae_dependents.rb
Fixes
Error: /opt/homebrew/Cellar/opencv/4.10.0_6 is not a directory
https://github.com/Homebrew/homebrew-core/actions/runs/10853013996/job/30140781474#step:3:1535
> formulae_dependents: ignore even more failures from unbottled formulae

- lib/step.rb
The first error message is often found before the last 256 lines, so
isn't included in the annotation.
Let's adjust `#truncate_output` so it includes this error message if
found instead. Searching for error messages is a little naive, but it
matches the way `clang`, `gcc`, and `rustc` print error messages. We can
make this more sophisticated later if desired.
> Include first error message in GitHub annotation

- lib/tests/formulae_dependents.rb
Fixes CI failure seen at Homebrew/homebrew-core#191307.
I think this is a much cleaner fix for this, but I'll need a bit more
time to work it out. In the meantime, let's do this to unblock the
aforementioned PR.
> formulae_dependents: install all built bottles

- lib/test_bot.rb
We still have a few bottles with missing attestations, but our CI
doesn't catch it because dependents are installed with
`HOMEBREW_DEVELOPER` unset.
Let's find out what those bottles are by ensuring we verify attestations
when installing bottles.
Also, remove `PYTHONDONTWRITEBYTECODE` because setting it here doesn't
do anything.
> Set `HOMEBREW_VERIFY_ATTESTATIONS`

- lib/tests/formulae_dependents.rb
We shouldn't fail CI if we fail to install an unbottled dependent, even
when we're not building from source.
Fixes failures seen at https://github.com/Homebrew/homebrew-core/actions/runs/10956242397/job/30553837181?pr=189352
> formulae_dependents: ignore more unbottled errors

- lib/tests/formulae_dependents.rb
The `texlive` bottle is gigantic and has about a thousand dependencies.
This tends to make GitHub-hosted runners run out of storage by the time
they get around to testing it, particularly since it comes late in the
alphabet (and we test dependents in alphabetical order).
To try to minimise usage of our self-hosted runner, let's test `texlive`
as early as possible to increase the chances of the runner having
sufficient storage to be able to test `texlive`.
> formulae_dependents: improve `texlive` handling

- lib/tests/formulae.rb
We've deprecated this, so this is now causing an error.
> Remove `rmtree` call

- lib/test_bot.rb
The CI machines for 3rd-party taps might not have a gh token and may fail to verify attestations, which is the case for us in https://github.com/osrf/homebrew-simulation/issues/2815.
Follow-up to https://github.com/Homebrew/homebrew-test-bot/pull/1230.
> Don't verify attestations for 3rd-party taps

- lib/test_bot.rb
We're regularly hitting rate limits in Homebrew/core after we started
verifying all these attestations, so let's try to limit doing it for
now.
> Verify attesations only during formula build step

- lib/tests/formulae.rb
Fixes
Error: A `brew install --formula gh` process has already locked /opt/homebrew/Cellar/gh.
Please wait for it to finish or terminate it to continue.
Homebrew/homebrew-core#192550
https://github.com/Homebrew/homebrew-core/actions/runs/11133201051/job/30938871245?pr=192550#step:3:53
> tests/formulae: skip attestation verification when building `gh`

- lib/tests/formulae.rb
Unfortunately #1247 was not sufficient.
https://github.com/Homebrew/homebrew-core/actions/runs/11133201051/job/30950399155?pr=192550#step:3:60
> tests/formulae: skip attestation verification when building `gh` (again)

- lib/tests/formulae.rb
This should hopefully be the last of these?
https://github.com/Homebrew/homebrew-core/actions/runs/11133201051/job/30951261825?pr=192550#step:3:44
Follow-up to #1247 and #1248.
> tests/formulae: skip attestation verification when bottle-reinstalling `gh`

- lib/tests/cleanup_before.rb
Should help us get rid of the strange warnings seen in [^1]. `aws/tap/aws-sam-cli` calls `opoo` unconditionally once evaluated [^2]. The tap `aws/tap` is installed on GitHub-hosted runners, and we evaluate all formulae when determining the dependents of testing formulae.
A more ideal and comprehensive solution would be to untap all unneeded taps by (recursively) determining which taps are actually needed by the formulae in the testing tap, but that requires evaluating all formulae in the testing tap and can be a bit more work. And in the end, for third-party taps, doing that will still not eliminate the warnings if a dependency has an unconditional `opoo` call like that. So for now, I'm restricting the cleanup to `homebrew/core`.
[^1]: …
> cleanup_before: untap unneeded taps on GitHub-hosted runners

- lib/tests/cleanup_before.rb
Reverts Homebrew/homebrew-test-bot#1250
> Revert "cleanup_before: untap unneeded taps on GitHub-hosted runners"

- lib/test_cleanup.rb
Take 2 at #1250; fixes https://github.com/Homebrew/homebrew-test-bot/pull/1250#issuecomment-2389466333.
The existing logic for moving files can silently fail when some files to move have a same name. This can be revealed as follows:
```console
$ mv -fv /opt/homebrew/Library/Taps/hashicorp/homebrew-tap /opt/homebrew/Library/Taps/azure/homebrew-bicep /opt/homebrew/Library/Taps/aws/homebrew-tap /private/tmp/d20241005-13189-6pyqe7
/opt/homebrew/Library/Taps/hashicorp/homebrew-tap -> /private/tmp/d20241005-13189-6pyqe7/homebrew-tap
/opt/homebrew/Library/Taps/azure/homebrew-bicep -> /private/tmp/d20241005-13189-6pyqe7/homebrew-bicep
mv: rename /opt/homebrew/Library/Taps/aws/homebrew-tap to /private/tmp/d20241005-13189-6pyqe7/homebrew-tap: Directory not empty
```
Fix that by creating a temporary …
> test_cleanup: fix moving of same-named files

- lib/test_cleanup.rb
- lib/test_cleanup.rbi
Will resolve failing checks in https://github.com/Homebrew/brew/pull/18517
These PRs need to merged together to work. (I can also update the linked PR to support both constants and methods as an intermediate step.)
> Replace removable constants with overridable methods

- lib/test_formulae.rb
`test-bot` is erroneously skipping builds for dependents of formulae
with `:all` bottles when the formula with an `:all` bottle has a test
dependency that isn't bottled.
See, for example:
https://github.com/Homebrew/homebrew-core/actions/runs/11278840144/job/31382054266#step:3:33
In the above example, `sfcgal` depends on `cgal`, and `cgal` has an
`:all` bottle and a `:test` dependency on `qt`, which is not yet bottled
on Sequoia. We should be ok with building a bottle for `sfcgal` in this
case.
> test_formulae: relax bottle requirement for test deps of `:all` bottles

- lib/test_formulae.rb
We don't need to throw out our cached bottle if the only dependencies
that have changed are build- or test-only.
> test_formulae: relax cache invalidation criteria

- lib/tests/formulae.rb
Since Homebrew/brew#18784 `brew uninstall` requires the `--ignore-dependencies` option to be used explicitly.
Fixes failure seen at https://github.com/Homebrew/homebrew-core/actions/runs/11889490048/job/33126293058?pr=198065.
> tests/formulae: add now-mandatory `--ignore-dependencies` option

- lib/tests/formulae.rb
One more fix like https://github.com/Homebrew/homebrew-test-bot/pull/1305.
Fixes failure seen at https://github.com/Homebrew/homebrew-core/actions/runs/11889979173/job/33128643880?pr=198048.
> tests/formulae: add missing `--ignore-dependencies` option

- lib/tests/formulae_dependents.rb
One more (and hopefully last) fix like #1305 and #1306. When we test dependents of multiple formulae, a dependent of one formula being tested can happen to be a dependency of another formula being tested. In this case, we need the `--ignore-dependencies` option to force removal of the dependent/dependency formula. When testing the dependents of the removed formula, `brew install --only-dependencies` ensures that it is reinstalled.
Fixes failure seen at https://github.com/Homebrew/homebrew-core/actions/runs/11923246241/job/33242018653?pr=198240.
> tests/formulae_dependents: another `--ignore-dependencies` fix

- lib/tests/formulae.rb
The `#livecheckable?` method for formulae/casks/resources is being renamed to `#livecheck_defined?` (https://github.com/Homebrew/brew/pull/18839). This updates related method calls, so we can deprecate `#livecheckable?`.
I've set this as a draft until the related brew PR is merged. The `odeprecated` calls for `#livecheckable?` are currently commented out and I will enable them in a follow-up PR (after this is merged).
> Update `#livecheckable?` usage

- .github/workflows/tests.yml
The previous commit doesn't exist.
> workflows/tests: fix cache action commit

- .github/workflows/tests.yml
Avoid template injection by using environment variables to represent template values.
> workflows/tests: fix template-injection zizmor findings

- lib/tests/formulae.rb
We recently modified the behavior of `brew livecheck` to skip packages in the tap's autobump list, so this change is causing autobumped formulae to fail the `brew livecheck` part of CI testing. This adds the `--autobump` option to the `brew livecheck` call, which will ensure that livecheck doesn't skip autobumped formulae.
> formulae: use livecheck --autobump option

- lib/tests/formulae_dependents.rb
I don't think we need to test these.
> formulae_dependents: skip implicit dependencies

- lib/tests/formulae.rb
- lib/tests/formulae_dependents.rb
Should unblock Homebrew/homebrew-core#206855.
> tests/formulae{,_dependents}: add special handling for `bash`

- lib/tests/formulae.rb
Should fix https://github.com/Homebrew/homebrew-test-bot/pull/1394#issuecomment-2646861220.
> tests/formulae: fix `bash` cleanup not being run

- lib/test_runner.rb
- lib/tests/packages_detect.rb
Rework of https://github.com/Homebrew/homebrew-test-bot/pull/1006 now that there is more linux support for casks.
> feat: scope detection to all packages

- lib/tests/packages_detect.rb
Fixes
Error: Parameter 'file': Expected type Pathname, got type String with value "Formula/s/systemd.rb"
https://github.com/Homebrew/homebrew-core/actions/runs/13921083284/job/38954279815#step:4:29
> packages_detect: fix typechecking error

- lib/tests/formulae.rb
This is essentially the same change as #1305, #1306, and #1307.
Fixes https://github.com/Homebrew/homebrew-core/actions/runs/13925253960/job/38968023209#step:5:64
> tests/formulae: add another `--ignore-dependencies` flag

- lib/step.rb
- avoid picking up GitHub annotations when looking for the first error
message
- print the CPU architecture in annotation titles on Linux to
distinguish x86_64 from arm64
> lib/step: improve annotation output

- .github/workflows/sync-default-branches.yml
- .github/workflows/tests.yml
- lib/test_cleanup.rb
- lib/tests/formulae_detect.rb
Port various changes from other repositories and make fixes to support the default `main` branch for both homebrew-test-bot and other taps by default.
> Use `main` as the default branch.

- lib/test_bot.rb
This is a nicer default that will adjust appropriately for the number of cores in a given runner.
> test_bot: set download concurrency to auto.

- cmd/test-bot.rb
- lib/test_bot.rb
The idea here is to pass `--concurrent-downloads` to `brew test-bot`
invocations unless a label is applied, which would help unblock
Homebrew/homebrew-core#231723.
It would also allow external tap authors to test it in their own taps if
desired.
Compantion to Homebrew/homebrew-core#231897
> cmd/test-bot: add `--concurrent-downloads` flag

- .github/workflows/tests.yml
Potential fix for [https://github.com/Homebrew/homebrew-test-bot/security/code-scanning/9](https://github.com/Homebrew/homebrew-test-bot/security/code-scanning/9)
To fix the problem, you should add a `permissions` block to the `rspec` job, specifying the minimal permissions required for the job to run successfully. If the job only needs to read repository contents (which is typical for CI jobs running tests), set `contents: read`. If it needs additional permissions (e.g., to create issues or update pull requests), add those as needed. The change should be made in the `.github/workflows/tests.yml` file, specifically by adding the `permissions` block under the `rspec` job, at the same level as `strategy`, `name`, and `runs-on`.
_Suggested fixes powered by Copilot Autofix. Review carefully …
> Potential fix for code scanning alert no. 9: Workflow does not contain permissions

- lib/tests/formulae.rb
This will be useful for PRs that touch large numbers of formulae, since
it allows you to more easily tell how much work CI has done, and how
much work there might be left to do.
> tests/formulae: print message about testing progress
